<div class="account-login login-container">
    <div id="login_box" class="login_box">
        <div class="c-logo">
            <img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt=""/>
        </div>
        <div class="login">
           <!-- <div class="page-title">
                <p class="welcome"><?php //echo $this->__('WELCOME TO OUR WHOLESALE PORTAL') ?></p>
                <p align="center"><?php //echo $this->__('RESET PASSWORD.') ?></p>
            </div> -->
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
                <?php echo $this->getBlockHtml('formkey'); ?>

                <div class="registered-users">
                    <div class="content">
					    <div class="page-title">
                <!--<p class="welcome"><?php //echo $this->__('WELCOME TO OUR WHOLESALE PORTAL') ?></p>-->
                         <p align="center" style="font-size: 18px;"><?php echo $this->__('RESET PASSWORD') ?></p>
                        </div>
                        <ul class="form-list">
                            <li>
                                <div class="text-left input-field email">
                                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="text-left input-field pwd">
                                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    </div>
                    <div class="buttons-set">
                       <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset Password')); ?>" class="button"><span><span><?php echo $this->__('Reset Password'); ?></span></span></button>

                    </div>
                </div>

            </form>
            <script type="text/javascript">
                //<![CDATA[
                var dataForm = new VarienForm('form-validate', true);
                //]]>
            </script>
        </div>

    </div>

</div>


