 <?php
 $collection = $this->chatList();
 $customer = $this->getCustomerDetail();
 $focusReply = '';
 $cid = Mage::app()->getRequest()->getParam('cid');
 if($customer->getId() == $cid){
 $focusReply = 'focus-reply';                   
 }
 ?>
 
<script type="text/javascript">
 
</script>
 <!----***************Message Section Starts Here***************------->
        <?php
		//$collection = $this->getMessages();
		
		
        //$totalMsg = $collection->getSize();
		$totalMsg = count($collection);
		//$this->getLastMessages();
        if ($totalMsg > 0) {
            ?>
           
			<div>
            <ul class="list-group" id='chatListBox' style="max-height:350px;overflow:scroll;overflow-x:hidden;" >
                <?php
                foreach ($collection as $message) {
				      $customerId = $message['customer_id'];
				      $customer = $this->getCustomerDetail();
                     ?>
                     <li class="list-group-item"> 
                    <?php
                   
                    if ($message['sent_by'] == 'customer') {
                        $seenClass = 'glyphicon-arrow-up';
                        if($message['seen'] == 1){
                           $seenClass = 'glyphicon-saved'; 
                        }
                        ?>  
						    <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/customer/edit/id/".$customerId)?>">
                            <span>
                                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>profile_image/default/profile.jpg" style="height:30px;width:30px;">
                            </span> 
							</a>
                            <b><?php echo ucfirst($customer->getFirstname());?></b> : <span style="color:#333;font-size:11px;"><?php echo $message['message']; ?></span>
							
                    <?php } else {
                        if($message['seen'] != '1'){
                        Mage::helper('halox_salesagent')->updateSeen($message->getId());
                        }
                        ?>
                            <span>
                                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>profile_image/<?php echo $message['image'];?>" style="height:30px;width:30px;">
                            </span> 
                            <b><?php //echo $message->getName(); ?>You</b> : <span style="color:#333;font-size:11px;"><?php echo $message['message']; ?></span>     
                        <?php
                        $seenClass = 'glyphicon-arrow-down';
                         if($message['seen'] == 1){
                                $seenClass = 'glyphicon-saved'; 
                         }
                    }
					 if($message['seen'] != '1'){
                        Mage::helper('halox_salesagent')->updateSeen($message['id']);
                      }
					
					?>
					<span class='sent-at'><?php echo Mage::helper('halox_salesagent')->formatSentTime($message['sent_at']);  ?></span>
				
                            <div style="width:100%;float:right;text-align:right;font-style:italic;" ><span class="glyphicon <?php echo $seenClass;?>"></span></div>
                    </li>
					
                    <?php
                }
                ?>				
            </ul>
			<div style="float:right;height:50px;padding:5px;"> 
					<a href="javascript:void(0);" onclick="loadChat('<?php echo $customerId; ?>');"><span class="glyphicon glyphicon-refresh"></span> Refresh</a>
			</div>
			<div style="width:100%;margin-top:15px;margin-bottom:15px;"></div>
			<div id="replyBox" style="width:99%;">
                            <p><textarea id="chatText" name="chatText" class="<?php echo $focusReply; ?>" onkeypress="sendOnEnter(event, '<?php echo $customer->getId(); ?>')"  style="width:100%;height:180px;"></textarea></p>
			<p><input type="checkbox" name="enterCheck" id="sendenter" /> <span style="color:#2B1B17">Send on enter keypress</span></p>
			<p><input type="button" class='sendMessage' name="chat" onclick="textMsg('<?php echo $customer->getId(); ?>')" value="Send" id="replyChat"></p>
			</div>
			</div>
            <?php
        }else{
        ?>
		<p style="color:green">No Conversation Found.</p>
		<?php
		}
		?>
        <!----***************Message Section Ends Here***************------->
<style>
.sendMessage{
    display: inline-block;
    margin-bottom: 0;
    font-weight: 400;
    text-align: center;
    vertical-align: middle;
    cursor: pointer;
    background-image: none;
    border: 1px solid transparent;
    white-space: nowrap;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    border-radius: 4px;
	color: #fff;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, .25);
    background-color: #08c;
    border-color: #08c;
	width:180px;
}
.sent-at{
font-size:9px !important;
margin-right:5px;
color:#999;
font-style:italic;
float:right;
}
.focus-reply{
    border:1px solid red;    
}
</style>