<!-- multistep form -->
<div class="account-create">
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="error_msg"></div>
    <div id="tab1" class="clearfix">
        <form name="registration_account_create" action="<?php echo $this->getUrl('registration/account/createpost'); ?>" method="post" id="Firstform-validate">
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" id="form_key" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" class="customer_id" name="customer_id" />

            <h4 class="step"><?php echo $this->__('Step 1 of 3') ?></h4>

            <ul class="form-list gray-bg padding-top">
                <li class="fields input-field">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li class="input-field">
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="input-field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" id="first_telephone" maxlength="20" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="validate-mobileno input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                    </div>
                </li>
            </ul>

            <ul class="form-list gray-bg">
                <li class="fields input-field">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
            <?php
            $collection = Mage::getModel('cms/block')->getCollection()
                    ->addFieldToFilter('identifier', array('like' => 'registration_' . '%'))
                    ->addFieldToFilter('is_active', 1);

            if (!empty($collection)) {
                $blockCount = $collection->count();
                $i = 0;
                foreach ($collection as $key => $value) {
                    $_blockId = $value->getIdentifier();
                    $_blockTitle = $value->getTitle();
                    $posReq = strpos($_blockId, 'registration_required');
                    $posNotReq = strpos($_blockId, 'registration_notrequired');

                    if ($posReq === false) {
                        $reqFlag = false;
                    }

                    if ($posNotReq === false) {
                        $reqFlag = true;
                    }
                    ?>
                    <div class="t-c clearfix">
                        <div class="input-box">
                            <input type="checkbox" id="step1_<?php echo $_blockId; ?>" name="step1_<?php echo $_blockId; ?>" value="1" title="<?php echo $_blockTitle ?>" class="checkbox <?php
            if ($reqFlag) {
                echo "required-entry";
            }
                    ?>">
                            <a href="javascript:void(0)" data-toggle="modal" data-target=".termsCondition_step1_<?php echo $i; ?>" style="color:gray;"><?php echo $_blockTitle; ?></a>
                        </div>

                    </div>
                    <div class="modal fade termsCondition_step1_<?php echo $i; ?>" id="step1_<?php echo $_blockId; ?>" role="dialog">
                        <div class="modal-dialog user-agreement">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title"><?php echo $_blockTitle; ?></h4>
                                </div>


                                <div class="modal-body" style =" max-height: 500px; overflow-y: auto;">
                                    <?php
                                    echo $this->getLayout()->createBlock('cms/block')->setBlockId($_blockId)->toHtml();
                                    ?>
                                </div>


                              <div class="modal-footer">
                                 <!--    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
                              </div>  
                            </div>
                         </div>
                    </div>

                    <?php
                    $i++;
                }
            }
            ?>
            <div class="btm-btn clearfix">
                <a href="javascript:void(0)" class="pull-left btn-back" id="back_login">&lt; Back</a>
                <button type="button" name="next" id="personal_info" class="btn btn-success pull-right">Next</button>
            </div>
        </form>
    </div>
    <div id="tab2" class="clearfix none">
        <form name="registration_account_create" action="<?php echo $this->getUrl('registration/account/createpost'); ?>" method="post" id="secondform-validate">
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" id="form_key" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

            <?php if ($this->getShowAddressFields()): ?>
                <div class="fieldset">
                    <input type="hidden" id="create_address" name="create_address" value="1" />
                    <input type="hidden" class="customer_id" name="customer_id" />
                    <input type="hidden" class="password_hash" name="password_hash" />
                    <input type="hidden" id="firstname_add" name="firstname_add" />
                    <input type="hidden" id="lastname_add" name="lastname_add" />
                    <input type="hidden" name="telephone" id="telephone"/>

                    <h4 class="step"><?php echo $this->__('Step 2 of 3') ?></h4>
                    <ul class="form-list gray-bg padding-top">
                        <li class="fields">
                            <div class="field">
                                <label for="company"><?php echo $this->__('Company') ?></label>
                                <div class="input-box">
                                    <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                </div>
                            </div>
                        </li>
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="wide">
                            <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?> 1" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                            </div>
                        </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="wide">
                                <label for="street_<?php echo $_i; ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                                <div class="input-box">
                                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </li>
                        <?php endfor; ?>
                        <li class="fields address clearfix">
                            <div class="field">
                                <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                <div class="input-box">
                                    <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                                </div>
                            </div>
                            <div class="field widthcity padd5rt">
                                <label for="region_id" class="required"><?php echo $this->__('State/Province') ?></label>
                                <div class="input-box">
                                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select">
                                        <option value=""><?php echo $this->__('Please select state') ?></option>
                                        <?php
                                        $this->setData('country_id', 'US'); // or 'FR'..., default is 'US'
                                        $regions = $this->getRegionCollection();
                                        foreach ($regions as $region) {
                                            echo "<option value='" . $region['region_id'] . "'>" . $region['name'] . "</option>";
                                        }
                                        ?>

                                    </select>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                        //]]>
                                    </script>
                                    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                            </div>
                            <div class="field widthcity padd5lt">
                                <div class="input-box">
                                    <label for="country" class="required"><i class="icon-country"></i><?php echo $this->__('Country') ?><em>*</em></label>
                                    <?php echo $this->getCountryHtmlSelect() ?>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                <div class="input-box">
                                    <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                </div>
                            </div>

                        </li>
                    </ul>
                    <input type="hidden" name="default_billing" id="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" id="default_shipping"  value="1" />
                </div>
            <?php endif; ?>

            <div class="btm-btn clearfix">
                <a href="javascript:void(0)" class="pull-left btn-back previous">&lt; Back</a>
                <button type="button" name="next" id="address_info" class="btn btn-success pull-right">Next</button>
            </div>

        </form>
    </div>
    <div id="tab3" class="clearfix none">
        <form name="registration_account_create" action="<?php echo $this->getUrl('registration/account/createpost'); ?>" method="post" id="form-validate">
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" id="form_key" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" class="customer_id" name="customer_id" />
             <input type="hidden" class="password_hash" name="password_hash" />
            
            <?php
            echo $this->getLayout()->createBlock('amcustomerattr/customer_fields')->setTemplate('registration/amasty/amcustomerattr/wholesale_customer_fields.phtml')->toHtml();
            echo $this->getLayout()->createBlock('amcustomerattr/customer_fields_relations')->setParts($column)->setTemplate('amasty/amcustomerattr/relations.phtml')->toHtml();
            ?>

            <div class="btm-btn clearfix">
                <a href="javascript:void(0)" class="pull-left btn-back previous">&lt; Back</a>
<!--                <button type="submit" name="next" id="" class="btn btn-success pull-right">FINISH <i class="fa fa-chevron-circle-right" aria-hidden="true">.</i></button>-->
                <button type="submit" value="Submit" class="btn btn-success pull-right">FINISH </button>
            </div>
            <input type="hidden" name="addi_info" id="addi_info">
        </form>

    </div>
    <div id="LoadingImage" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/loader9.gif') ?>"></div>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
<?php if ($this->getShowAddressFields()): ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
<?php endif; ?>
        //]]>
    </script>
</div>


<script type="text/javascript">
  Validation.add('wholesale-mobile-validation','Please enter a valid phone number. For example (123) 456-7890 or 123-456-7890.',function(the_field_value){
        if(the_field_value == 'baz')
        {
            return true;
        }
        return false;
    });  
    
    
</script>   


<script type="text/javascript">
//<![CDATA[ 
// telephone no validations[Start] 
jQuery('#first_telephone').keyup(function () {
    this.value = this.value.replace(/[^0-9.]/g,'');
});
if(Validation) {
Validation.addAllThese([
['validate-mobileno','Enter correct mobile number',
function(v){
if(v.length > 0){
if( v.length >=9 && v.length <=20){
    return true;
   }else{
        return false;
   }
return true;

}else {
return false;
}

}
]])};
 var dataForm = new VarienForm('form-validate', true);
//]]>


// telephone no validations[Ends] 
</script>