<style>
	.range, .range-line, .field-100, .filternew, ._region{display:inline-block; padding-right:15px; box-sizing:border-box;}
	.range-line input, ._region input{margin-left:5px;}
	.field-100{padding-top:10px;box-sizing:border-box;}
	
</style>

<?php 
$filters = array();
if($this->getRequest()->getParam('filter')){
    $filterParams = base64_decode($this->getRequest()->getParam('filter'));
    parse_str(urldecode($filterParams), $filters);  
}

?>


<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width:50%;"><h3 class="icon-head head-adminhtml-taxexcisereport">Excise Tax Report</h3></td>
                <td class="form-buttons"></td>
            </tr>
        </tbody>
    </table>
</div>
<div id ="taxexcisereportGridNew">
<div class="filternew">
	<div class="range">
            <div class="range-line date">
                <span class="label">From:</span>
                <input type="text" name="created_at[from]" id="taxexcisereportGridNew_filternew_created_at_from" value="<?php if(isset($filters['created_at']['from']) && $filters['created_at']['from']):?><?php echo $filters['created_at']['from']?><?php endif?>" class="input-text no-changes">
                <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif',array('_secure'=>true))?>" alt="" class="v-middle" id="taxexcisereportGridNew_filternew_created_at_from_trig" title="Date selector">
            </div>
            <div class="range-line date">
                <span class="label">To :</span>
                <input type="text" name="created_at[to]" id="taxexcisereportGridNew_filternew_created_at_to" value="<?php if(isset($filters['created_at']['to']) && $filters['created_at']['to']):?><?php echo $filters['created_at']['to']?><?php endif?>" class="input-text no-changes">
                <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif',array('_secure'=>true))?>" alt="" class="v-middle" id="taxexcisereportGridNew_filternew_created_at_to_trig" title="Date selector">
            </div>
        </div>
        <input type="hidden" name="created_at[locale]" value="en_US">
        
        
        <script type="text/javascript">
            Calendar.setup({
                inputField : "taxexcisereportGridNew_filternew_created_at_from",
                ifFormat : "%m/%e/%Y",
                button : "taxexcisereportGridNew_filternew_created_at_from_trig",
                align : "Bl",
                singleClick : true
            });
            Calendar.setup({
                inputField : "taxexcisereportGridNew_filternew_created_at_to",
                ifFormat : "%m/%e/%Y",
                button : "taxexcisereportGridNew_filternew_created_at_to_trig",
                align : "Bl",
                singleClick : true
            });

            $("taxexcisereportGridNew_filternew_created_at_to_trig").observe("click", showCalendar);
            $("taxexcisereportGridNew_filternew_created_at_from_trig").observe("click", showCalendar);

            function showCalendar(event){
                var element = event.element(event);
                var offset = $(element).viewportOffset();
                var scrollOffset = $(element).cumulativeScrollOffset();
                var dimensionsButton = $(element).getDimensions();
                var index = $("widget-chooser").getStyle("zIndex");

                $$("div.calendar").each(function(item){
                    if ($(item).visible()) {
                        var dimensionsCalendar = $(item).getDimensions();

                        $(item).setStyle({
                            "zIndex" : index + 1,
                            "left" : offset[0] + scrollOffset[0] - dimensionsCalendar.width
                                + dimensionsButton.width + "px",
                            "top" : offset[1] + scrollOffset[1] + dimensionsButton.height + "px"
                        });
                    };
                });
            };
        </script>
		
        <?php
        $stateObj = Mage::getModel('directory/region')->getResourceCollection()->addCountryFilter('US')->load();
        $regions = $stateObj->getData()

        ?>
		
        <div class="_region">
            <span class="label">Region :</span>
            <select name="region" id ="taxexcisereportGridNew_filternew_region" class="no-changes">
                <option value=""> Select Region</option>
                <?php foreach($regions as $index =>$regionArr):?>
                <option <?php if(isset($filters['region']) && $filters['region'] && ($regionArr['name'] == $filters['region'])): ?>selected="selected"<?php endif ?> value="<?php echo $regionArr['name'] ?>"> <?php echo $regionArr['name'] ?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <button id="id_search_here" title="Refresh" type="button" class="scalable task" onclick="taxexcisereportGridJsObject.doFilterNew()" style=""><span><span><span>Refresh</span></span></span></button>
</div>

	