<?php
/**
 * MageParts
 * 
 * NOTICE OF LICENSE
 * 
 * This code is copyrighted by MageParts and may not be reproduced
 * and/or redistributed without a written permission by the copyright 
 * owners. If you wish to modify and/or redistribute this file please
 * contact us at info@mageparts.com for confirmation before doing
 * so. Please note that you are free to modify this file for personal
 * use only.
 *
 * If you wish to make modifications to this file we advice you to use
 * the "local" file scope in order to aviod conflicts with future updates. 
 * For information regarding modifications see http://www.magentocommerce.com.
 *  
 * DISCLAIMER
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE 
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * @category   MageParts
 * @package    MageParts_RestrictCategories
 * @copyright  Copyright (c) 2009 MageParts (http://www.mageparts.com/)
 * @author 	   MageParts Crew
 */
?>

<?php $helper = Mage::helper('restrictcategories'); ?>
<?php $rule = $this->getRule(); ?>
<?php $workingStoreId = $helper->getStoreId(); ?>

<div class="entry-edit">
	<?php echo $this->getFormObject()->getHtml() ?>
</div>

<script type="text/javascript">

	// get fieldset
	var mpRestrictCategories = {
		
		toggleDefaultValues : function(checkboxEl)
		{
			var customerIdsEl = $('restrictions_customer_ids');
			var customerGroupsEl = $('restrictions_customer_group_id');
			
			if (customerIdsEl.parentNode) {
				toggleValueElements(checkboxEl, customerIdsEl.parentNode);
			}
			
			if (customerGroupsEl.parentNode) {
				toggleValueElements(checkboxEl, customerGroupsEl.parentNode);
			}
		}
		
	};
	
	<?php if (($helper->getMagentoVersion() < 1.4) && (($rule->getStoreId() == $workingStoreId) || $workingStoreId == 0)) : ?>
	var intiCustomerIdsEl = $('restrictions_customer_ids');
	var initCustomerGroupsEl = $('restrictions_customer_group_id');
	
	if (initCustomerGroupsEl) {
		initCustomerGroupsEl.disabled = false;
	}
	
	if (intiCustomerIdsEl) {
		intiCustomerIdsEl.disabled = false;
	}
	<?php endif; ?>

</script>