<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
$enabled = Mage::getStoreConfig('homeslider/general/enabled', $code);
$type = Mage::getStoreConfig('homeslider/general/type', $code);
$static_block_id = Mage::getStoreConfig('homeslider/general/static_block_id', $code);
if($enabled == 1){
?>
<div id="slideshow">
<?php
    echo $this->getLayout()->createBlock('cms/block', $static_block_id, array(
        	'cache_lifetime' => null,
        	'cache_tags' => array(Mage_Catalog_Model_Product::CACHE_TAG)
    	)
    )->setBlockId($static_block_id)->toHtml();
?>
</div>
<?php    
} else {
?>
<?php
}
?>
