<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();

    $currentProduct = Mage::registry('current_product') 
        ? Mage::registry('current_product') : '';

    $isBundleProduct = 0;
    if($currentProduct){
        $isBundleProduct = $currentProduct->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE
            ? 1 : 0;
    }

    $currentAction = $this->getAction()->getFullActionName();
    $isProductConfigurePage = $currentAction == 'checkout_cart_configure' ? 1 : 0;
?>
<div id="loading-mask">
<div class ="background-overlay"></div>
	<p id="loading_mask_loader" class="loader">
        <i class="ajax-loader large animate-spin"></i>
	</p>
</div>
<div id="after-loading-success-message">
    <div class ="background-overlay"></div>
        <div id="success-message-container" class="loader">
            <!--<button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>-->
            <div class="ajaxbox">
                <div class="ajax-header">
                    <button title="Close" role="button" class="ui-state-default ui-dialog-titlebar-close close-popup" type="button"><span class="ui-icon"></span></button>
                </div>
                <div class="ajaxloading clearfix">
                    <div class="msg-box">
                        <?php echo $this->__("Product was successfully added to your shopping cart.") ?>
                    </div>
                        <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                </div>
                <div class="ajax-footer clearfix">
                    <div class="ajaxloadingbuttons">
                        
                        <button type="button" name="continue_shopping" id="continue_shopping" class="button btn-cart" >
                        <span><span>
                        <?php $continueshoppingtext = Mage::getStoreConfig('ajaxcart/addtocart/continueshoppingtext', $code);?>
                        <?php if (!empty($continueshoppingtext)): ?>
                                <?php echo $continueshoppingtext; ?>
                        <?php else:?>
                                <?php echo $this->__("Continue") ?>
                        <?php endif;?>
                        </span></span></button>
                        
                        <button type="button" name="finish_and_checkout" id="finish_and_checkout" class="button btn-cart" ><span><span>
                        <?php $gotocarttext = Mage::getStoreConfig('ajaxcart/addtocart/gotocarttext', $code);?>
                        <?php if (!empty($gotocarttext)): ?>
                                <?php echo $gotocarttext; ?>
                        <?php else:?>
                                <?php echo $this->__("Go to cart page") ?>
                        <?php endif;?>
                        </span></span></button>
                    </div>
                </div>
            </div>
        <?php
    /*   related items  */
    ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ajax-popup-crosssell-items')->toHtml(); ?>
    <?php //echo $this->getLayout()->createBlock('checkout/cart_crosssell')->setTemplate('checkout/cart/crosssell-ajax.phtml')->toHtml(); ?>
    <?php 

    /*$_product = $this->getProduct(); 
    if(count($_product->getUpSellProductIds()) > 0) : */
    //echo $this->getChildHtml('related_products');
    //echo $this->getLayout()->createBlock('product.info.upsell')->setTemplate('catalog/product/list/upsell-ajaxcart.phtml')->toHtml(); 
        /* endif;    */
    /*related items*/
     ?>
        </div>

    </div>	
<script type='text/javascript'>
	
    var isBundleProductPage = <?php echo $isBundleProduct?>;
    var isProductConfigurePage  =   <?php echo $isProductConfigurePage?>;

    jQuery('#finish_and_checkout').click(function(){
        try{
            parent.location.href = '<?php echo $this->getUrl('checkout/cart') ?>';
        }catch(err){
            location.href = '<?php echo $this->getUrl('checkout/cart') ?>';
        }
    });

	jQuery('#continue_shopping').click(function(){
        
        //for bundle product make continue button redirect to the same page
        if(isBundleProductPage && !isProductConfigurePage){

            try{
                parent.location.href = '<?php echo Mage::helper('core/url')->getCurrentUrl();?>';
            }catch(err){
                location.href = '<?php echo Mage::helper('core/url')->getCurrentUrl();?>';
            }

        }else{
            
            jQuery('#after-loading-success-message').fadeOut(200);
            clearTimeout(ajaxcart_timer);
            setTimeout(function(){
                jQuery('#after-loading-success-message .timer').text(ajaxcart_sec);
            }, 1000);    
        }

    });

    if(isBundleProductPage && !isProductConfigurePage){
        jQuery('.close-popup').click(function(e){

            e.stopImmediatePropagation();

            try{
                parent.location.href = '<?php echo Mage::helper('core/url')->getCurrentUrl();?>';
            }catch(err){
                location.href = '<?php echo Mage::helper('core/url')->getCurrentUrl();?>';
            }

        });        
    }

    


</script>