<?php
/**
 * sort invoice items in natural order
 */
?>
<?php  $_order = $this->getOrder() ?>
<p class="order-links"><a href="<?php echo $this->getPrintAllInvoicesUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print All Invoices') ?></a></p>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
<h2 class="sub-title"><?php echo $this->__('Invoice #') ?><?php echo $_invoice->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintInvoiceUrl($_invoice) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print Invoice') ?></a></h2>
<h3 class="table-caption"><?php echo $this->__('Items Invoiced') ?></h3>
<table class="data-table" id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><span class="nobr"><?php echo $this->__('Qty Invoiced') ?></span></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
    </tfoot>
    <?php 
    $_itemsCollection = $_invoice->getAllItems();

    foreach ($_itemsCollection as $item) {
        
        if ($item->getOrderItem()) {
            $itemType = $item->getOrderItem()->getProductType();
        } else {
            $itemType = $item->getProductType();
        }
        
        if($parentItem = $item->getOrderItem()->getParentItem()){
                
            if ($parentItem->getOrderItem()) {
                $parentType = $parentItem->getOrderItem()->getProductType();
            } else {
                $parentType = $parentItem->getProductType();
            }
            if($parentType == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE){
                $_items[] = $item;
            }
        }elseif($itemType != Mage_Catalog_Model_Product_Type::TYPE_BUNDLE){
            $_items[] = $item;
        }

        
    }

    //sort cart items in natural order(CASE-INSENSITIVE)
    usort($_items, function($a, $b){
        return strnatcasecmp($a->getName(),$b->getName());
    });



    ?>
    <?php $_count = count($_items) ?>
    <?php foreach ($_items as $_item): ?>
    <tbody>
        <?php 

        if ($_item->getOrderItem()) {
            $type = $_item->getOrderItem()->getProductType();
        } else {
            $type = $_item->getProductType();
        }

        $renderer = $this->getItemRenderer($type);
        
        //if cart item is child of a bundle item use bundle item renderer 
        //instead of default one
        if($parentItem = $_item->getOrderItem()->getParentItem()){
            if ($parentItem->getOrderItem()) {
                $parentType = $parentItem->getOrderItem()->getProductType();
            } else {
                $parentType = $parentItem->getProductType();
            }
            
            if($parentType == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE){
                $renderer = $this->getItemRenderer(Mage_Catalog_Model_Product_Type::TYPE_BUNDLE);
            }
        }

        $renderer->setItem($_item);
        ?>

        <?php echo $renderer->toHtml()?>
    </tbody>
    <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-invoice-table-<?php echo $_invoice->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php echo $this->getInvoiceCommentsHtml($_invoice)?>
<?php endforeach; ?>
