<div class="dealsheader">
<div class="wrap" id="ja-header">
<div class="main">
<img style="margin-left: 20px;" src="<?php echo $this->getSkinUrl('images/header.png');?>" usemap="#Teaser" alt="" />
<map id="Teaser" name="Teaser"><area shape="rect" alt="The Halocigs" title="" coords="7,1,382,125" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>" target="_self" /></map>
</div>                                                                                             
</div>

<!--<div>
<img src="<?php echo $this->getSkinUrl('images/header.png')?>" alt="Halocigs" />
</div>-->