<script type="text/javascript">
   jQuery(document).ready(function(){
      
   var count=0; // to count blank fields
   jQuery('.ja-bot').hide();
   jQuery('#ja-footer').hide();
   jQuery('.zopim').hide();
   
   var param = document.URL.split('?v=')[1];
   if(param=="groupon" || param=="undefined"){
          jQuery('.social_living').hide();
          jQuery('.battery_colortr').show();
          jQuery('#battery_color').val(0);
          jQuery('.grouponleft').show();
          jQuery('.livingsocialleft').hide();
          jQuery('.disclaimer').hide();
   }else{
          jQuery('.social_living').show();
          jQuery('.battery_colortr').hide();
          jQuery('#flavor_option_2').val(0); 
          jQuery('.grouponleft').hide();
          jQuery('.livingsocialleft').show();  
          jQuery('.disclaimer').hide();
   }
   
   jQuery(".messages").delay(10000).hide(0);
   jQuery('.grouponleft').show();
   
   jQuery("#deal_name").change(function () {
         if(jQuery('#deal_name').val()==1){
          jQuery('.social_living').show();
          jQuery('.battery_colortr').hide();
          jQuery('#flavor_option_2').val(0); 
          jQuery('.grouponleft').hide();
          jQuery('.livingsocialleft').show();
         }else{
          jQuery('.social_living').hide();
          jQuery('.battery_colortr').show();
          jQuery('#battery_color').val(0);
          jQuery('.grouponleft').show();
          jQuery('.livingsocialleft').hide();
         }
   });
   jQuery("#country").change(function () {
     //alert(jQuery('#country').val());return false;
         if(jQuery('#country').val()!="United States"){
         jQuery('.stateadd').show();
          jQuery('.stateselect').hide();
          
         }else{
          jQuery('.stateselect').show();
          jQuery('.stateadd').hide();
         }   
     });
   
   jQuery(".submit_btn").click(function(event){
         
      if(jQuery('.first_name').val()==""){
            alert("*Please Enter First Name*");
            return false;
      }
      if(jQuery('#telephone').val()==""){    
           alert("*Please Enter Your Last Name*");
             return false;
      }
       if(jQuery('#address').val()==""){
          alert("*Please Enter Address*");
          return false;
      }
      /*if(jQuery('#company').val()==""){
          alert("*Please Enter Address  Line 2*");
          return false;
      } */
     
      if(jQuery('#country').val()==""){
          alert("*Please Select Country*");
          return false;
      }
      if(jQuery('#city').val()==""){
          alert("*Please Enter Your City Name*");
          return false;
      }
      if(jQuery('#zip').val()==""){
          alert("*Please Enter Your Postal Code*");
          return false;
      }
     
      if((jQuery('#country').val()!="United States" && jQuery('.state1').val()=="")||(jQuery('#country').val()=="United States" && jQuery('.state2').val()=="") ){
             alert("*Please Enter/select State*");
             return false;
         }
      
      if(jQuery('.last_name').val()==""){
          alert("*Please Enter Email*");
          return false;
      }
     
      if (!validateEmail(jQuery('.last_name').val())) {
          alert('Invalid Email Address');
          jQuery('.last_name').focus();
          return false;
       }
       else{
             return true;
         }
   //fetching radio button by name
     var radio_check = jQuery('.rad');
     
     //fetching all inputs with same class name text_field and an html tag textarea 
     var input_field = jQuery('.text_field');
     var text_area = jQuery('textarea');
     
     //validating radio button
     if(radio_check[0].checked== false && radio_check[1].checked== false){
      var y = 0;
     }
     else{
      var y = 1; 
     }
     //for loop to count blank inputs 
     for(var i=input_field.length;i>count;i--){
     if(input_field[i-1].value==''|| text_area.value=='')
         {
             count = count + 1;
         }
     else{            
             count = 0;
         }
     }
         //Notifying validation 
         if(count!=0||y==0){
         
             alert("*All Fields are mandatory*");
             event.preventDefault();    
             }
             else{            
                 return true;
             }
   });
   /*---------------------------------------------------------*/
     jQuery(".next_btn").click(function(){           //Function runs on NEXT button click  
          
          var param = document.URL.split('?v=')[1];
         // alert(param);
          if(param=="groupon" || param=="undefined"){
             if(jQuery('#voucher').val()==""){    
                 alert("*Please Enter Voucher Code*");
                 return false;
             }
             if(jQuery('#type_of_kit').val()==""){    
                 alert("*Please Select One Type Of Kit*");
                 return false;
             }
             if(jQuery('#battery_color').val()=="0"){    
                 alert("*Please Select One Battery Color*");
                 return false;
             }
             if(jQuery('#flavor_option_1').val()==""){    
                 alert("*Please Select One e-Liquid Flavor Options*");
                 return false;
             }
              jQuery('.disclaimer').show();
          }
          else if(param=="groupon_mock" || param=="undefined"){
             if(jQuery('#voucher').val()==""){    
                 alert("*Please Enter Voucher Code*");
                 return false;
             }
             
             if(jQuery('#sample_pack').val()=="0"){    
                 alert("*Please Select One Sample Pack*");
                 return false;
             }
             if(jQuery('#fax').val()==0){    
                 alert("*Please Select One e-Liquid Nicotine Level*");
                 return false;
             }
              jQuery('.disclaimer').show();
          }
          else if(param=="living-social"){
             if(jQuery('#voucher').val()==""){    
                 alert("*Please Enter Voucher Code*");
                 return false;
             }
             if(jQuery('#type_of_kit').val()==""){    
                 alert("*Please Select One On The Go Starter Kit Options*");
                 return false;
             }
             if(jQuery('#flavor_option_1').val()==""){    
                 alert("*Please Select One e-Liquid Flavor Options (Bottle 1)*");
                 return false;
             }
             if(jQuery('#flavor_option_2').val()==""){    
                 alert("*Please Select One e-Liquid Flavor Options (Bottle 2)*");
                 return false;
             }
             if(jQuery('#fax').val()==0){    
                 alert("*Please Select One e-Liquid Nicotine Level*");
                 return false;
             }
             jQuery('.disclaimer').show();
          }
          else{
               if(jQuery('#voucher').val()==""){    
                 alert("*Please Enter Voucher Code*");
                 return false;
             }
             if(jQuery('#type_of_kit').val()==""){    
                 alert("*Please Select One Type Of Kit*");
                 return false;
             }
             if(jQuery('#battery_color').val()=="0"){    
                 alert("*Please Select One Battery Color*");
                 return false;
             }
             if(jQuery('#flavor_option_1').val()==""){    
                 alert("*Please Select One e-Liquid Flavor Options*");
                 return false;
             }
              jQuery('.disclaimer').show();
          }
     jQuery(this).parent().next().fadeIn('slow');
     jQuery(this).parent().css({'display':'none'});
     jQuery('.active').next().addClass('active');
     });
     
     jQuery(".pre_btn").click(function(){            //Function runs on PREVIOUS button click 
     jQuery('.disclaimer').hide();
     jQuery(this).parent().prev().fadeIn('slow');
     jQuery(this).parent().css({'display':'none'});
     jQuery('.active:last').removeClass('active');
     });
   });
   
   
   function validateEmail(sEmail) {
      // alert("Validate email");
    var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
   if (pattern.test(sEmail)) {
       return true;
   }else{
       return false;
   }    
   }
    
</script>
<?php if($_REQUEST['v']=="living-social"){?>
<div class="leftcontent">
   <div class="livingsocialleft">
      <div class="dealimage">
         <img src="<?php echo $this->getSkinUrl('images/living_social.png');?>" class="imagesize" alt="">
      </div>
      <div class="dealcontent">
         <h2>Halo On The Go Kit for just<span> $25.00</span></h2>
         <h3>with your Living Social Code.</h3>
         <h3>Regular Price <span> $50.96</span></h3>
         <h3>Offer Includes:</h3>
         <div class="contentotgkit">
            <ul>
               <li>
                  <div class="otgkit">
                     1 Halo On The Go Kit - 
                     <span style="color:#0092ff;font-size: 14px;">
                        <ol style="margin-left:10px;">
                           <li>(1) Lithium Ion Rechargeable Battery</li>
                           <li>(1) USB Charger</li>
                           <li>(1) Carry Case</li>
                           <li>(3) Prefilled Cartomizers = Approx. 3 Packs of Traditional Cigs.(18mg/ml)</li>
                        </ol>
                     </span>
                  </div>
               </li>
               <li>
                  <div class="otgkit1">(1) 5 Pack of Blank Cartomizers (Classic Tan)</div>
               </li>
               <li>
                  <div class="otgkit2">(2) Halo American Made E-Liquid Bottles - Available in 5 Nicotine Strengths.</div>
               </li>
            </ul>
         </div>
         <h2 class="ordershipping"><span style="color: #bd0606;">*</span><span>Orders are charged $2.99 shipping for fulfillment to the US, excluding Hawaii and Alaska.</span></h2>
      </div>
   </div>
</div>
<?php }else if($_REQUEST['v']=="groupon_mock"){ ?>
<!--<div class="grouponleft">
   <div class="dealimage">
       <img src="<?php echo $this->getSkinUrl('images/eliquid.png');?>" class="imagesize" alt="">
   </div>
   <div class="dealcontent">
       <h2>e-Liquid Sample Pack -<span> $xx.00</span></h2>
       <h3>with your Groupon Code.</h3>
       <h3>Regular Price <span> $xx.xx</span></h3>
       <h3>Offer Includes:</h3>
       <div class="otgkit">It's the Perfect way to try the best flavors from the United States' Top Vaping Brands.<br/>Your choice of 6 delicious bottles of American Made e-Liquid from the Halo or eVo collection.<br/>Each Sample Pack is available in the below flavors and is available in 5 Nicotine Strengths. </div>            
   </div>
   </div>-->
<div class="leftcontenteliq" >
   <div class="grouponlefteliq">
      <div class="dealimage">
         <img alt="" class="imagesizeeliq" src="<?php echo $this->getSkinUrl('images/eliquid.png');?>">
      </div>
      <div class="dealcontenteliq">
         <h2 class="h2eliq">e-Liquid Sample Pack -<span> $19.99</span></h2>
         <h3>with your Groupon Code.</h3>
         <h3>Regular Price <span> $35.94</span></h3>
         <h3>Offer Includes:</h3>
         <div class="otgkiteliq">It's the Perfect way to try the best flavors from the United States' Top Vaping Brands.<br>Your choice of 6 delicious bottles of American Made e-Liquid from the Halo or eVo collection.<br>Each Sample Pack is available in the below flavors and is available in 5 Nicotine Strengths. </div>
      </div>
   </div>
</div>
<div class="middleeliq">
   <span class="haloeliq"> Tobacco/Menthol Variety Sample Pack </span> <br>
   Tribeca (sweet tobacco)<br>
   Torque Tobacco (classic tobacco)<br>
   Malibu (pina colada)<br>
   SubZero (X strength menthol)<br>
   Belgian Cocoa (chocolate)<br>
   Kringle's Curse (peppermint)
   <br>
   <br>
   <div class="evoeliq">
      <div class="evoeliq1">
         <span class="evoinner">Caf&eacute; Sample Pack</span><br>
         Caramel Coconut Cookie<br>
         Apple Cinnamon<br>
         Tangerine Swirl<br>
         Nutty Caramel<br>
         Apple Pom Smothie<br>
         Hazzelnut Cappuccino<br>
      </div>
      <div class="evoeliq2">
         <span class="evoinner"> Harvest Sample Pack</span><br>
         Wild watermelon<br>
         Cantaloupia<br>
         Backwoods Blueberry<br>
         Berry Blast<br>
         Grape Vape<br>
         Summer Peach
      </div>
   </div>
</div>
<?php }else{?>  
<div class="leftcontent">
   <div class="grouponleft">
      <div class="dealimage">
         <img src="<?php echo $this->getSkinUrl('images/groupon.png');?>" class="imagesize" alt="">
      </div>
      <div class="dealcontent">
         <h2>Halo Triton Starter Kit -<span> $19.99</span></h2>
         <h3>with your Groupon Code.</h3>
         <h3>Regular Price <span> $34.99</span></h3>
         <h3>Offer Includes:</h3>
         <div class="otgkit">(1) Halo Triton Starter Kit - (1) 650 mAh Rechargeable Battery, (1) USB Charger, (1) 2.4ml Refillable Tank, (1) 7ml Bottle of American Made Halo e-Liquid</div>
      </div>
   </div>
</div>
<?php
   }
   ?>
<?php
   if($_REQUEST['v']=="groupon_mock"){?>
<div class="rightcontenteq">
<?php }else{?>
<div class="rightcontent">
   <?php }?>
   <form class="regform" method="post" action="<?php echo Mage::getUrl('frontdeals/index/post') ?>" id="edit_form">
      <fieldset id="first">
         <!--        success -->
         <?php
            if(isset($_REQUEST['msg'])!="success"){
               
            ?>
         <?php if($_REQUEST['v']=="living-social"){ ?>
         <div class="titletest">
            <p>Enter Your Living Social Code in the coupon code box below.</p>
            <p>Select Your Preferences</p>
            <p>Then CLICK, "Continue"</p>
         </div>
         <div class="headerwhite">
            step 1
            <p>Enter Living Social Code:</p>
         </div>
         <div class="inputvoucher"><input type="text" class="required-entry input-text" value="" name="voucher" id="voucher">
            <input type="hidden" name="deal_name" id="deal_name" value="1" >
         </div>
         <div class="headerwhite">
            step 2
            <p>On The Go Starter Kit Options:</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="type_of_kit" id="type_of_kit">
               <option selected="selected" value="">Select One</option>
               <option value="1">Tobacco - Tribeca</option>
               <option value="2">Menthol - Mystic</option>
            </select>
         </div>
         <div class="headerwhite">
            step 3
            <p>e-Liquid Flavor Options (Bottle 1):</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="flavor_option_1" id="flavor_option_1">
               <option selected="selected" value="">Select One</option>
               <option value="1">Tribeca (sweet tobacco)</option>
               <option value="2">Torque 56 (classic tobacco)</option>
               <option value="3">Malibu (pina colada)</option>
               <option value="4">SubZero (X strength menthol)</option>
               <option value="5">Belgian Cocoa (chocolate)</option>
               <option value="6">Kringle's Curse (peppermint)</option>
            </select>
         </div>
         <div class="headerwhite">
            step 4
            <p>e-Liquid Flavor Options (Bottle 2):</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="flavor_option_2" id="flavor_option_2">
               <option selected="selected" value="">Select One</option>
               <option value="1">Tribeca (sweet tobacco)</option>
               <option value="2">Torque 56 (classic tobacco)</option>
               <option value="3">Malibu (pina colada)</option>
               <option value="4">SubZero (X strength menthol)</option>
               <option value="5">Belgian Cocoa (chocolate)</option>
               <option value="6">Kringle's Curse (peppermint)</option>
            </select>
         </div>
         <div class="headerwhite">
            step 5
            <p>e-Liquid Nicotine Level:</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="fax" id="fax">
               <option selected="selected" value="0">Select One</option>
               <!--<option value="1">00MG: No Nicotine</option>-->
               <option value="2">06MG: Super Light Strength</option>
               <option value="3">12MG: Light Strength</option>
               <option value="4">18MG: Regular Strength</option>
               <option value="5">24MG: X-Strength</option>
            </select>
         </div>
         <div class="headerwhite">step 6</div>
         <input type="button" name="next" class="next_btn" value="Continue" />
         <?php  } else if($_REQUEST['v']=="groupon_mock"){ ?> 
         <div class="titletest">
            <p>Enter Your Groupon Code here below.</p>
            <p>Select Your Preferences</p>
            <p>Then CLICK, "Continue"</p>
         </div>
         <div class="headerwhiteg">
            step 1
            <p>Enter Groupon Code</p>
         </div>
         <div class="inputvoucher"><input type="text" class="required-entry input-text" value="" name="voucher" id="voucher">
            <input type="hidden" name="deal_name" id="deal_name" value="2" >
         </div>
         <input type="hidden" name="type_of_kit" value="0"> 
         <div class="headerwhiteg">
            step 2
            <p>Select Sample Pack Flavor</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="sample_pack" id="sample_pack">
               <option selected="selected" value="0">Select One</option>
               <option value="1">Caf&eacute; Sample Pack</option>
               <option value="2">Tobacco/Menthol Variety Sample Pack</option>
               <option value="3">Harvest Sample Pack</option>
            </select>
         </div>
         <div class="headerwhiteg">
            step 3
            <p>Select Nicotine Level </p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="fax" id="fax">
               <option selected="selected" value="0">Select One</option>
               <option value="1">00MG: No Nicotine</option>
               <option value="2">06MG: Super Light Strength</option>
               <option value="3">12MG: Light Strength</option>
               <option value="4">18MG: Regular Strength</option>
               <option value="5">24MG: X-Strength</option>
            </select>
         </div>
         <div class="headerwhiteg">step 4</div>
         <input type="button" name="next" class="next_btn" value="Continue"  />    
         <?php }else{  ?>
         <div class="titletest">
            <p>Enter Your Groupon Code in the coupon code box below.</p>
            <p>Select Your Preferences</p>
            <p>Then CLICK, "Continue"</p>
         </div>
         <div class="headerwhiteg">
            step 1
            <p>Enter Groupon Code:</p>
         </div>
         <div class="inputvoucher"><input type="text" class="required-entry input-text" value="" name="voucher" id="voucher">
            <input type="hidden" name="deal_name" id="deal_name" value="0" >
         </div>
         <input type="hidden" name="type_of_kit" value="0">
         <div class="headerwhite">
            step 2
            <p>Battery Color Options</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="battery_color" id="battery_color">
               <option selected="selected" value="0">Choose One</option>
               <option value="1">Black</option>
               <option value="4">Blue</option>
               <option value="3">Red</option>
               <option value="5">Iridescence</option>
               <option value="2">Titanium</option>
            </select>
         </div>
         <div class="headerwhiteg">
            step 3
            <p>e-Liquid Flavor Options:</p>
         </div>
         <div class="inputvoucher">
            <select class="required-entry select" name="flavor_option_1" id="flavor_option_1">
               <option selected="selected" value="">Select One</option>
               <option value="7">Tobacco - Tribeca</option>
               <option value="8">Menthol - SubZero</option>
            </select>
         </div>
         <div class="headerwhiteg">step 4</div>
         <input type="button" name="next" class="next_btn" value="Continue" />
         <?php  }  ?>
         <?php
            }else{
                ?>
         <h2 style="width: 333px;">Thank you for redeeming your voucher. 
            <br><br><br>
            <span>Click <a href="<?php echo Mage::getBaseUrl();?>frontdeals?v=<?php $params = $this->getRequest()->getParams(); echo $params["v"];?>">here</a> to redeem another voucher.</span> 
         </h2>
         <?php
            }
            ?>   
      </fieldset>
      <!--        success -->
      <?php if($_REQUEST['v']=="groupon_mock"){?>
      <fieldset id="secondfieldseteliq">
         <h2 class="title">Shipping Information:</h2>
         <div class="fieldlablevalue">
            <h3>First Name</h3>
            <input type="text" class="first_name required-entry input-text required-entry" value="" name="first_name" id="first_name" style="width:213px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>Last Name</h3>
            <input type="text" class="first_name required-entry input-text required-entry" value="" name="telephone" id="telephone" style="width:213px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>Street Address</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="address" id="address" style="width:213px;"> 
            <input type="text" class="required-entry input-text required-entry" value="" name="company" id="company" style="width:213px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>City</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="city" id="city" style="width:213px;">
         </div>
         <div class="fieldlablevalue">
            <h3>State</h3>
            <span class="stateadd" style="display:none;" >
            <input type="text" class="required-entry input-text required-entry" value="" name="state1" id="state1" style="width:213px;"></span>
            <span class="stateselect">
               <select  class="state2 validate-select" title="State/Province" name="state" id="state" defaultvalue="0" style="width:213px;">
                  <option value="">Please select region, state or province</option>
                  <option value="Alabama" title="Alabama">Alabama</option>
                  <option value="Alaska" title="Alaska">Alaska</option>
                  <option value="American Samoa" title="American Samoa">American Samoa</option>
                  <option value="Arizona" title="Arizona">Arizona</option>
                  <option value="Arkansas" title="Arkansas">Arkansas</option>
                  <option value="Armed Forces Africa" title="Armed Forces Africa">Armed Forces Africa</option>
                  <option value="Armed Forces Americas" title="Armed Forces Americas">Armed Forces Americas</option>
                  <option value="Armed Forces Canada" title="Armed Forces Canada">Armed Forces Canada</option>
                  <option value="Armed Forces Europe" title="Armed Forces Europe">Armed Forces Europe</option>
                  <option value="Armed Forces Middle East" title="Armed Forces Middle East">Armed Forces Middle East</option>
                  <option value="Armed Forces Pacific" title="Armed Forces Pacific">Armed Forces Pacific</option>
                  <option value="California" title="California">California</option>
                  <option value="Colorado" title="Colorado">Colorado</option>
                  <option value="Connecticut" title="Connecticut">Connecticut</option>
                  <option value="Delaware" title="Delaware">Delaware</option>
                  <option value="District of Columbia" title="District of Columbia">District of Columbia</option>
                  <option value="Federated States Of Micronesia" title="Federated States Of Micronesia">Federated States Of Micronesia</option>
                  <option value="Florida" title="Florida">Florida</option>
                  <option value="Georgia" title="Georgia">Georgia</option>
                  <option value="Guam" title="Guam">Guam</option>
                  <option value="Hawaii" title="Hawaii">Hawaii</option>
                  <option value="Idaho" title="Idaho">Idaho</option>
                  <option value="Illinois" title="Illinois">Illinois</option>
                  <option value="Indiana" title="Indiana">Indiana</option>
                  <option value="Iowa" title="Iowa">Iowa</option>
                  <option value="Kansas" title="Kansas">Kansas</option>
                  <option value="Kentucky" title="Kentucky">Kentucky</option>
                  <option value="Louisiana" title="Louisiana">Louisiana</option>
                  <option value="Maine" title="Maine">Maine</option>
                  <option value="Marshall Islands" title="Marshall Islands">Marshall Islands</option>
                  <option value="Maryland" title="Maryland">Maryland</option>
                  <option value="Massachusetts" title="Massachusetts">Massachusetts</option>
                  <option value="Michigan" title="Michigan">Michigan</option>
                  <option value="Minnesota" title="Minnesota">Minnesota</option>
                  <option value="Mississippi" title="Mississippi">Mississippi</option>
                  <option value="Missouri" title="Missouri">Missouri</option>
                  <option value="Montana" title="Montana">Montana</option>
                  <option value="Nebraska" title="Nebraska">Nebraska</option>
                  <option value="Nevada" title="Nevada">Nevada</option>
                  <option value="New Hampshire" title="New Hampshire">New Hampshire</option>
                  <option value="New Jersey" title="New Jersey">New Jersey</option>
                  <option value="New Mexico" title="New Mexico">New Mexico</option>
                  <option value="New York" title="New York">New York</option>
                  <option value="North Carolina" title="North Carolina">North Carolina</option>
                  <option value="North Dakota" title="North Dakota">North Dakota</option>
                  <option value="Northern Mariana Islands" title="Northern Mariana Islands">Northern Mariana Islands</option>
                  <option value="Ohio" title="Ohio">Ohio</option>
                  <option value="Oklahoma" title="Oklahoma">Oklahoma</option>
                  <option value="Oregon" title="Oregon">Oregon</option>
                  <option value="Palau" title="Palau">Palau</option>
                  <option value="Pennsylvania" title="Pennsylvania">Pennsylvania</option>
                  <option value="Puerto Rico" title="Puerto Rico">Puerto Rico</option>
                  <option value="Rhode Island" title="Rhode Island">Rhode Island</option>
                  <option value="South Carolina" title="South Carolina">South Carolina</option>
                  <option value="South Dakota" title="South Dakota">South Dakota</option>
                  <option value="Tennessee" title="Tennessee">Tennessee</option>
                  <option value="Texas" title="Texas">Texas</option>
                  <option value="Utah" title="Utah">Utah</option>
                  <option value="Vermont" title="Vermont">Vermont</option>
                  <option value="Virgin Islands" title="Virgin Islands">Virgin Islands</option>
                  <option value="Virginia" title="Virginia">Virginia</option>
                  <option value="Washington" title="Washington">Washington</option>
                  <option value="West Virginia" title="West Virginia">West Virginia</option>
                  <option value="Wisconsin" title="Wisconsin">Wisconsin</option>
                  <option value="Wyoming" title="Wyoming">Wyoming</option>
               </select>
            </span>
         </div>
         <div class="fieldlablevalue">
            <h3>Postal Code</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="zip" id="zip" style="width:213px;">                  
         </div>
         <div class="fieldlablevalue">
            <h3>Country</h3>
            <select title="Country" class="validate-select" id="country" name="country" style="width: 213px;">
               <option value=""> </option>
               <option value="Afghanistan">Afghanistan</option>
               <option value="Åland Islands">Åland Islands</option>
               <option value="Albania">Albania</option>
               <option value="Algeria">Algeria</option>
               <option value="American Samoa">American Samoa</option>
               <option value="Andorra">Andorra</option>
               <option value="Angola">Angola</option>
               <option value="Anguilla">Anguilla</option>
               <option value="Antarctica">Antarctica</option>
               <option value="Antigua and Barbuda">Antigua and Barbuda</option>
               <option value="Argentina">Argentina</option>
               <option value="Armenia">Armenia</option>
               <option value="Aruba">Aruba</option>
               <option value="Australia">Australia</option>
               <option value="Austria">Austria</option>
               <option value="Azerbaijan">Azerbaijan</option>
               <option value="Bahamas">Bahamas</option>
               <option value="Bahrain">Bahrain</option>
               <option value="Bangladesh">Bangladesh</option>
               <option value="Barbados">Barbados</option>
               <option value="Belarus">Belarus</option>
               <option value="Belgium">Belgium</option>
               <option value="Belize">Belize</option>
               <option value="Benin">Benin</option>
               <option value="Bermuda">Bermuda</option>
               <option value="Bhutan">Bhutan</option>
               <option value="Bolivia">Bolivia</option>
               <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
               <option value="Botswana">Botswana</option>
               <option value="Bouvet Island">Bouvet Island</option>
               <option value="Brazil">Brazil</option>
               <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
               <option value="British Virgin Islands">British Virgin Islands</option>
               <option value="Brunei">Brunei</option>
               <option value="Bulgaria">Bulgaria</option>
               <option value="Burkina Faso">Burkina Faso</option>
               <option value="Burundi">Burundi</option>
               <option value="Cambodia">Cambodia</option>
               <option value="Cameroon">Cameroon</option>
               <option value="Canada">Canada</option>
               <option value="Cape Verde">Cape Verde</option>
               <option value="Cayman Islands">Cayman Islands</option>
               <option value="Central African Republic">Central African Republic</option>
               <option value="Chad">Chad</option>
               <option value="Chile">Chile</option>
               <option value="China">China</option>
               <option value="Christmas Island">Christmas Island</option>
               <option value="Cocos [Keeling] Islands">Cocos [Keeling] Islands</option>
               <option value="Colombia">Colombia</option>
               <option value="Comoros">Comoros</option>
               <option value="Congo - Brazzaville">Congo - Brazzaville</option>
               <option value="Congo - Kinshasa">Congo - Kinshasa</option>
               <option value="Cook Islands">Cook Islands</option>
               <option value="Costa Rica">Costa Rica</option>
               <option value="Côte d’Ivoire">Côte d’Ivoire</option>
               <option value="Croatia">Croatia</option>
               <option value="Cuba">Cuba</option>
               <option value="Cyprus">Cyprus</option>
               <option value="Czech Republic">Czech Republic</option>
               <option value="Denmark">Denmark</option>
               <option value="Djibouti">Djibouti</option>
               <option value="Dominica">Dominica</option>
               <option value="Dominican Republic">Dominican Republic</option>
               <option value="Ecuador">Ecuador</option>
               <option value="Egypt">Egypt</option>
               <option value="El Salvador">El Salvador</option>
               <option value="Equatorial Guinea">Equatorial Guinea</option>
               <option value="Eritrea">Eritrea</option>
               <option value="Estonia">Estonia</option>
               <option value="Ethiopia">Ethiopia</option>
               <option value="Falkland Islands">Falkland Islands</option>
               <option value="Faroe Islands">Faroe Islands</option>
               <option value="Fiji">Fiji</option>
               <option value="Finland">Finland</option>
               <option value="France">France</option>
               <option value="French Guiana">French Guiana</option>
               <option value="French Polynesia">French Polynesia</option>
               <option value="French Southern Territories">French Southern Territories</option>
               <option value="Gabon">Gabon</option>
               <option value="Gambia">Gambia</option>
               <option value="Georgia">Georgia</option>
               <option value="Germany">Germany</option>
               <option value="Ghana">Ghana</option>
               <option value="Gibraltar">Gibraltar</option>
               <option value="Greece">Greece</option>
               <option value="Greenland">Greenland</option>
               <option value="Grenada">Grenada</option>
               <option value="Guadeloupe">Guadeloupe</option>
               <option value="Guam">Guam</option>
               <option value="Guatemala">Guatemala</option>
               <option value="Guernsey">Guernsey</option>
               <option value="Guinea">Guinea</option>
               <option value="Guinea-Bissau">Guinea-Bissau</option>
               <option value="Guyana">Guyana</option>
               <option value="Haiti">Haiti</option>
               <option value="Heard Island and McDonald Islands">Heard Island and McDonald Islands</option>
               <option value="Honduras">Honduras</option>
               <option value="Hong Kong SAR China">Hong Kong SAR China</option>
               <option value="Hungary">Hungary</option>
               <option value="Iceland">Iceland</option>
               <option value="India">India</option>
               <option value="Indonesia">Indonesia</option>
               <option value="Iran">Iran</option>
               <option value="Iraq">Iraq</option>
               <option value="Ireland">Ireland</option>
               <option value="Isle of Man">Isle of Man</option>
               <option value="Israel">Israel</option>
               <option value="Italy">Italy</option>
               <option value="Jamaica">Jamaica</option>
               <option value="Japan">Japan</option>
               <option value="Jersey">Jersey</option>
               <option value="Jordan">Jordan</option>
               <option value="Kazakhstan">Kazakhstan</option>
               <option value="Kenya">Kenya</option>
               <option value="Kiribati">Kiribati</option>
               <option value="Kuwait">Kuwait</option>
               <option value="Kyrgyzstan">Kyrgyzstan</option>
               <option value="Laos">Laos</option>
               <option value="Latvia">Latvia</option>
               <option value="Lebanon">Lebanon</option>
               <option value="Lesotho">Lesotho</option>
               <option value="Liberia">Liberia</option>
               <option value="Libya">Libya</option>
               <option value="Liechtenstein">Liechtenstein</option>
               <option value="Lithuania">Lithuania</option>
               <option value="Luxembourg">Luxembourg</option>
               <option value="Macau SAR China">Macau SAR China</option>
               <option value="Macedonia">Macedonia</option>
               <option value="Madagascar">Madagascar</option>
               <option value="Malawi">Malawi</option>
               <option value="Malaysia">Malaysia</option>
               <option value="Maldives">Maldives</option>
               <option value="Mali">Mali</option>
               <option value="Malta">Malta</option>
               <option value="Marshall Islands">Marshall Islands</option>
               <option value="Martinique">Martinique</option>
               <option value="Mauritania">Mauritania</option>
               <option value="Mauritius">Mauritius</option>
               <option value="Mayotte">Mayotte</option>
               <option value="Mexico">Mexico</option>
               <option value="Micronesia">Micronesia</option>
               <option value="Moldova">Moldova</option>
               <option value="Monaco">Monaco</option>
               <option value="Mongolia">Mongolia</option>
               <option value="Montenegro">Montenegro</option>
               <option value="Montserrat">Montserrat</option>
               <option value="Morocco">Morocco</option>
               <option value="Mozambique">Mozambique</option>
               <option value="Myanmar [Burma]">Myanmar [Burma]</option>
               <option value="Namibia">Namibia</option>
               <option value="Nauru">Nauru</option>
               <option value="Nepal">Nepal</option>
               <option value="Netherlands">Netherlands</option>
               <option value="Netherlands Antilles">Netherlands Antilles</option>
               <option value="New Caledonia">New Caledonia</option>
               <option value="New Zealand">New Zealand</option>
               <option value="Nicaragua">Nicaragua</option>
               <option value="Niger">Niger</option>
               <option value="Nigeria">Nigeria</option>
               <option value="Niue">Niue</option>
               <option value="Norfolk Island">Norfolk Island</option>
               <option value="Northern Mariana Islands">Northern Mariana Islands</option>
               <option value="North Korea">North Korea</option>
               <option value="Norway">Norway</option>
               <option value="Oman">Oman</option>
               <option value="Palau">c</option>
               <option value="Palau">Palau</option>
               <option value="Palestinian Territories">Palestinian Territories</option>
               <option value="Panama">Panama</option>
               <option value="Papua New Guinea">Papua New Guinea</option>
               <option value="Paraguay">Paraguay</option>
               <option value="Peru">Peru</option>
               <option value="Philippines">Philippines</option>
               <option value="Pitcairn Islands">Pitcairn Islands</option>
               <option value="Poland">Poland</option>
               <option value="Portugal">Portugal</option>
               <option value="Puerto Rico">Puerto Rico</option>
               <option value="Qatar">Qatar</option>
               <option value="Réunion">Réunion</option>
               <option value="Romania">Romania</option>
               <option value="Russia">Russia</option>
               <option value="Rwanda">Rwanda</option>
               <option value="Saint Barthélemy">Saint Barthélemy</option>
               <option value="Saint Helena">Saint Helena</option>
               <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
               <option value="Saint Lucia">Saint Lucia</option>
               <option value="Saint Martin">Saint Martin</option>
               <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
               <option value="Saint Vincent and the Grenadines">Saint Vincent and the Grenadines</option>
               <option value="Samoa">Samoa</option>
               <option value="San Marino">San Marino</option>
               <option value="São Tomé and Príncipe">São Tomé and Príncipe</option>
               <option value="Saudi Arabia">Saudi Arabia</option>
               <option value="Senegal">Senegal</option>
               <option value="Serbia">Serbia</option>
               <option value="Seychelles">Seychelles</option>
               <option value="Sierra Leone">Sierra Leone</option>
               <option value="Singapore">Singapore</option>
               <option value="Slovakia">Slovakia</option>
               <option value="Slovenia">Slovenia</option>
               <option value="Solomon Islands">Solomon Islands</option>
               <option value="Somalia">Somalia</option>
               <option value="South Africa">South Africa</option>
               <option value="South Georgia and the South Sandwich Islands">South Georgia and the South Sandwich Islands</option>
               <option value="South Korea">South Korea</option>
               <option value="Spain">Spain</option>
               <option value="Sri Lanka">Sri Lanka</option>
               <option value="Sudan">Sudan</option>
               <option value="Suriname">Suriname</option>
               <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
               <option value="Swaziland">Swaziland</option>
               <option value="Sweden">Sweden</option>
               <option value="Switzerland">Switzerland</option>
               <option value="Syria">Syria</option>
               <option value="Taiwan">Taiwan</option>
               <option value="Tajikistan">Tajikistan</option>
               <option value="Tanzania">Tanzania</option>
               <option value="Thailand">Thailand</option>
               <option value="Timor-Leste">Timor-Leste</option>
               <option value="Togo">Togo</option>
               <option value="Tokelau">Tokelau</option>
               <option value="Tonga">Tonga</option>
               <option value="Trinidad and Tobago">Trinidad and Tobago</option>
               <option value="Tunisia">Tunisia</option>
               <option value="Turkey">Turkey</option>
               <option value="Turkmenistan">Turkmenistan</option>
               <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
               <option value="Tuvalu">Tuvalu</option>
               <option value="Uganda">Uganda</option>
               <option value="Ukraine">Ukraine</option>
               <option value="United Arab Emirates">United Arab Emirates</option>
               <option value="United Kingdom">United Kingdom</option>
               <option selected="selected" value="United States">United States</option>
               <option value="UY">UY</option>
               <option value="U.S. Minor Outlying Islands">U.S. Minor Outlying Islands</option>
               <option value="U.S. Virgin Islands">U.S. Virgin Islands</option>
               <option value="Uzbekistan">Uzbekistan</option>
               <option value="Vanuatu">Vanuatu</option>
               <option value="Vatican City">Vatican City</option>
               <option value="Venezuela">Venezuela</option>
               <option value="Vietnam">Vietnam</option>
               <option value="Wallis and Futuna">Wallis and Futuna</option>
               <option value="Western Sahara">Western Sahara</option>
               <option value="Yemen">Yemen</option>
               <option value="Zambia">Zambia</option>
               <option value="Zimbabwe">Zimbabwe</option>
            </select>
            <br>
         </div>
         <div class="fieldlablevalue">
            <h3>* Email</h3>
            <input type="text" class="last_name required-entry input-text required-entry" value="" name="last_name" id="last_name" style="width:213px;">                 
         </div>
         <br>
         <div class=""></div>
         <br>
         <input type="button" class="pre_btn" value="Previous" /> 
         <input type="submit" class="submit_btn" value="Submit" />
                 
      </fieldset>
      <?php }else{?>
      <fieldset id="secondfieldset">
         <h2 class="title">Shipping Information:</h2>
         <div class="fieldlablevalue">
            <h3>First Name</h3>
            <input type="text" class="first_name required-entry input-text required-entry" value="" name="first_name" id="first_name" style="width:333px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>Last Name</h3>
            <input type="text" class="first_name required-entry input-text required-entry" value="" name="telephone" id="telephone" style="width:333px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>Street Address</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="address" id="address" style="width:333px;"> 
            <input type="text" class="required-entry input-text required-entry" value="" name="company" id="company" style="width:333px;">                
         </div>
         <div class="fieldlablevalue">
            <h3>City</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="city" id="city" style="width:333px;">
         </div>
         <div class="fieldlablevalue">
            <h3>State</h3>
            <span class="stateadd" style="display:none;" >
            <input type="text" class="required-entry input-text required-entry" value="" name="state1" id="state1" style="width:333px;"></span>
            <span class="stateselect">
               <select style="" class="state2 validate-select" title="State/Province" name="state" id="state" defaultvalue="0" style="width:333px;">
                  <option value="">Please select region, state or province</option>
                  <option value="Alabama" title="Alabama">Alabama</option>
                  <option value="Alaska" title="Alaska">Alaska</option>
                  <option value="American Samoa" title="American Samoa">American Samoa</option>
                  <option value="Arizona" title="Arizona">Arizona</option>
                  <option value="Arkansas" title="Arkansas">Arkansas</option>
                  <option value="Armed Forces Africa" title="Armed Forces Africa">Armed Forces Africa</option>
                  <option value="Armed Forces Americas" title="Armed Forces Americas">Armed Forces Americas</option>
                  <option value="Armed Forces Canada" title="Armed Forces Canada">Armed Forces Canada</option>
                  <option value="Armed Forces Europe" title="Armed Forces Europe">Armed Forces Europe</option>
                  <option value="Armed Forces Middle East" title="Armed Forces Middle East">Armed Forces Middle East</option>
                  <option value="Armed Forces Pacific" title="Armed Forces Pacific">Armed Forces Pacific</option>
                  <option value="California" title="California">California</option>
                  <option value="Colorado" title="Colorado">Colorado</option>
                  <option value="Connecticut" title="Connecticut">Connecticut</option>
                  <option value="Delaware" title="Delaware">Delaware</option>
                  <option value="District of Columbia" title="District of Columbia">District of Columbia</option>
                  <option value="Federated States Of Micronesia" title="Federated States Of Micronesia">Federated States Of Micronesia</option>
                  <option value="Florida" title="Florida">Florida</option>
                  <option value="Georgia" title="Georgia">Georgia</option>
                  <option value="Guam" title="Guam">Guam</option>
                  <option value="Hawaii" title="Hawaii">Hawaii</option>
                  <option value="Idaho" title="Idaho">Idaho</option>
                  <option value="Illinois" title="Illinois">Illinois</option>
                  <option value="Indiana" title="Indiana">Indiana</option>
                  <option value="Iowa" title="Iowa">Iowa</option>
                  <option value="Kansas" title="Kansas">Kansas</option>
                  <option value="Kentucky" title="Kentucky">Kentucky</option>
                  <option value="Louisiana" title="Louisiana">Louisiana</option>
                  <option value="Maine" title="Maine">Maine</option>
                  <option value="Marshall Islands" title="Marshall Islands">Marshall Islands</option>
                  <option value="Maryland" title="Maryland">Maryland</option>
                  <option value="Massachusetts" title="Massachusetts">Massachusetts</option>
                  <option value="Michigan" title="Michigan">Michigan</option>
                  <option value="Minnesota" title="Minnesota">Minnesota</option>
                  <option value="Mississippi" title="Mississippi">Mississippi</option>
                  <option value="Missouri" title="Missouri">Missouri</option>
                  <option value="Montana" title="Montana">Montana</option>
                  <option value="Nebraska" title="Nebraska">Nebraska</option>
                  <option value="Nevada" title="Nevada">Nevada</option>
                  <option value="New Hampshire" title="New Hampshire">New Hampshire</option>
                  <option value="New Jersey" title="New Jersey">New Jersey</option>
                  <option value="New Mexico" title="New Mexico">New Mexico</option>
                  <option value="New York" title="New York">New York</option>
                  <option value="North Carolina" title="North Carolina">North Carolina</option>
                  <option value="North Dakota" title="North Dakota">North Dakota</option>
                  <option value="Northern Mariana Islands" title="Northern Mariana Islands">Northern Mariana Islands</option>
                  <option value="Ohio" title="Ohio">Ohio</option>
                  <option value="Oklahoma" title="Oklahoma">Oklahoma</option>
                  <option value="Oregon" title="Oregon">Oregon</option>
                  <option value="Palau" title="Palau">Palau</option>
                  <option value="Pennsylvania" title="Pennsylvania">Pennsylvania</option>
                  <option value="Puerto Rico" title="Puerto Rico">Puerto Rico</option>
                  <option value="Rhode Island" title="Rhode Island">Rhode Island</option>
                  <option value="South Carolina" title="South Carolina">South Carolina</option>
                  <option value="South Dakota" title="South Dakota">South Dakota</option>
                  <option value="Tennessee" title="Tennessee">Tennessee</option>
                  <option value="Texas" title="Texas">Texas</option>
                  <option value="Utah" title="Utah">Utah</option>
                  <option value="Vermont" title="Vermont">Vermont</option>
                  <option value="Virgin Islands" title="Virgin Islands">Virgin Islands</option>
                  <option value="Virginia" title="Virginia">Virginia</option>
                  <option value="Washington" title="Washington">Washington</option>
                  <option value="West Virginia" title="West Virginia">West Virginia</option>
                  <option value="Wisconsin" title="Wisconsin">Wisconsin</option>
                  <option value="Wyoming" title="Wyoming">Wyoming</option>
               </select>
            </span>
         </div>
         <div class="fieldlablevalue">
            <h3>Postal Code</h3>
            <input type="text" class="required-entry input-text required-entry" value="" name="zip" id="zip" style="width:333px;">                  
         </div>
         <div class="fieldlablevalue">
            <h3>Country</h3>
            <select title="Country" class="validate-select" id="country" name="country" style="width:333px;">
               <option value=""> </option>
               <option value="Afghanistan">Afghanistan</option>
               <option value="Åland Islands">Åland Islands</option>
               <option value="Albania">Albania</option>
               <option value="Algeria">Algeria</option>
               <option value="American Samoa">American Samoa</option>
               <option value="Andorra">Andorra</option>
               <option value="Angola">Angola</option>
               <option value="Anguilla">Anguilla</option>
               <option value="Antarctica">Antarctica</option>
               <option value="Antigua and Barbuda">Antigua and Barbuda</option>
               <option value="Argentina">Argentina</option>
               <option value="Armenia">Armenia</option>
               <option value="Aruba">Aruba</option>
               <option value="Australia">Australia</option>
               <option value="Austria">Austria</option>
               <option value="Azerbaijan">Azerbaijan</option>
               <option value="Bahamas">Bahamas</option>
               <option value="Bahrain">Bahrain</option>
               <option value="Bangladesh">Bangladesh</option>
               <option value="Barbados">Barbados</option>
               <option value="Belarus">Belarus</option>
               <option value="Belgium">Belgium</option>
               <option value="Belize">Belize</option>
               <option value="Benin">Benin</option>
               <option value="Bermuda">Bermuda</option>
               <option value="Bhutan">Bhutan</option>
               <option value="Bolivia">Bolivia</option>
               <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
               <option value="Botswana">Botswana</option>
               <option value="Bouvet Island">Bouvet Island</option>
               <option value="Brazil">Brazil</option>
               <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
               <option value="British Virgin Islands">British Virgin Islands</option>
               <option value="Brunei">Brunei</option>
               <option value="Bulgaria">Bulgaria</option>
               <option value="Burkina Faso">Burkina Faso</option>
               <option value="Burundi">Burundi</option>
               <option value="Cambodia">Cambodia</option>
               <option value="Cameroon">Cameroon</option>
               <option value="Canada">Canada</option>
               <option value="Cape Verde">Cape Verde</option>
               <option value="Cayman Islands">Cayman Islands</option>
               <option value="Central African Republic">Central African Republic</option>
               <option value="Chad">Chad</option>
               <option value="Chile">Chile</option>
               <option value="China">China</option>
               <option value="Christmas Island">Christmas Island</option>
               <option value="Cocos [Keeling] Islands">Cocos [Keeling] Islands</option>
               <option value="Colombia">Colombia</option>
               <option value="Comoros">Comoros</option>
               <option value="Congo - Brazzaville">Congo - Brazzaville</option>
               <option value="Congo - Kinshasa">Congo - Kinshasa</option>
               <option value="Cook Islands">Cook Islands</option>
               <option value="Costa Rica">Costa Rica</option>
               <option value="Côte d’Ivoire">Côte d’Ivoire</option>
               <option value="Croatia">Croatia</option>
               <option value="Cuba">Cuba</option>
               <option value="Cyprus">Cyprus</option>
               <option value="Czech Republic">Czech Republic</option>
               <option value="Denmark">Denmark</option>
               <option value="Djibouti">Djibouti</option>
               <option value="Dominica">Dominica</option>
               <option value="Dominican Republic">Dominican Republic</option>
               <option value="Ecuador">Ecuador</option>
               <option value="Egypt">Egypt</option>
               <option value="El Salvador">El Salvador</option>
               <option value="Equatorial Guinea">Equatorial Guinea</option>
               <option value="Eritrea">Eritrea</option>
               <option value="Estonia">Estonia</option>
               <option value="Ethiopia">Ethiopia</option>
               <option value="Falkland Islands">Falkland Islands</option>
               <option value="Faroe Islands">Faroe Islands</option>
               <option value="Fiji">Fiji</option>
               <option value="Finland">Finland</option>
               <option value="France">France</option>
               <option value="French Guiana">French Guiana</option>
               <option value="French Polynesia">French Polynesia</option>
               <option value="French Southern Territories">French Southern Territories</option>
               <option value="Gabon">Gabon</option>
               <option value="Gambia">Gambia</option>
               <option value="Georgia">Georgia</option>
               <option value="Germany">Germany</option>
               <option value="Ghana">Ghana</option>
               <option value="Gibraltar">Gibraltar</option>
               <option value="Greece">Greece</option>
               <option value="Greenland">Greenland</option>
               <option value="Grenada">Grenada</option>
               <option value="Guadeloupe">Guadeloupe</option>
               <option value="Guam">Guam</option>
               <option value="Guatemala">Guatemala</option>
               <option value="Guernsey">Guernsey</option>
               <option value="Guinea">Guinea</option>
               <option value="Guinea-Bissau">Guinea-Bissau</option>
               <option value="Guyana">Guyana</option>
               <option value="Haiti">Haiti</option>
               <option value="Heard Island and McDonald Islands">Heard Island and McDonald Islands</option>
               <option value="Honduras">Honduras</option>
               <option value="Hong Kong SAR China">Hong Kong SAR China</option>
               <option value="Hungary">Hungary</option>
               <option value="Iceland">Iceland</option>
               <option value="India">India</option>
               <option value="Indonesia">Indonesia</option>
               <option value="Iran">Iran</option>
               <option value="Iraq">Iraq</option>
               <option value="Ireland">Ireland</option>
               <option value="Isle of Man">Isle of Man</option>
               <option value="Israel">Israel</option>
               <option value="Italy">Italy</option>
               <option value="Jamaica">Jamaica</option>
               <option value="Japan">Japan</option>
               <option value="Jersey">Jersey</option>
               <option value="Jordan">Jordan</option>
               <option value="Kazakhstan">Kazakhstan</option>
               <option value="Kenya">Kenya</option>
               <option value="Kiribati">Kiribati</option>
               <option value="Kuwait">Kuwait</option>
               <option value="Kyrgyzstan">Kyrgyzstan</option>
               <option value="Laos">Laos</option>
               <option value="Latvia">Latvia</option>
               <option value="Lebanon">Lebanon</option>
               <option value="Lesotho">Lesotho</option>
               <option value="Liberia">Liberia</option>
               <option value="Libya">Libya</option>
               <option value="Liechtenstein">Liechtenstein</option>
               <option value="Lithuania">Lithuania</option>
               <option value="Luxembourg">Luxembourg</option>
               <option value="Macau SAR China">Macau SAR China</option>
               <option value="Macedonia">Macedonia</option>
               <option value="Madagascar">Madagascar</option>
               <option value="Malawi">Malawi</option>
               <option value="Malaysia">Malaysia</option>
               <option value="Maldives">Maldives</option>
               <option value="Mali">Mali</option>
               <option value="Malta">Malta</option>
               <option value="Marshall Islands">Marshall Islands</option>
               <option value="Martinique">Martinique</option>
               <option value="Mauritania">Mauritania</option>
               <option value="Mauritius">Mauritius</option>
               <option value="Mayotte">Mayotte</option>
               <option value="Mexico">Mexico</option>
               <option value="Micronesia">Micronesia</option>
               <option value="Moldova">Moldova</option>
               <option value="Monaco">Monaco</option>
               <option value="Mongolia">Mongolia</option>
               <option value="Montenegro">Montenegro</option>
               <option value="Montserrat">Montserrat</option>
               <option value="Morocco">Morocco</option>
               <option value="Mozambique">Mozambique</option>
               <option value="Myanmar [Burma]">Myanmar [Burma]</option>
               <option value="Namibia">Namibia</option>
               <option value="Nauru">Nauru</option>
               <option value="Nepal">Nepal</option>
               <option value="Netherlands">Netherlands</option>
               <option value="Netherlands Antilles">Netherlands Antilles</option>
               <option value="New Caledonia">New Caledonia</option>
               <option value="New Zealand">New Zealand</option>
               <option value="Nicaragua">Nicaragua</option>
               <option value="Niger">Niger</option>
               <option value="Nigeria">Nigeria</option>
               <option value="Niue">Niue</option>
               <option value="Norfolk Island">Norfolk Island</option>
               <option value="Northern Mariana Islands">Northern Mariana Islands</option>
               <option value="North Korea">North Korea</option>
               <option value="Norway">Norway</option>
               <option value="Oman">Oman</option>
               <option value="Palau">c</option>
               <option value="Palau">Palau</option>
               <option value="Palestinian Territories">Palestinian Territories</option>
               <option value="Panama">Panama</option>
               <option value="Papua New Guinea">Papua New Guinea</option>
               <option value="Paraguay">Paraguay</option>
               <option value="Peru">Peru</option>
               <option value="Philippines">Philippines</option>
               <option value="Pitcairn Islands">Pitcairn Islands</option>
               <option value="Poland">Poland</option>
               <option value="Portugal">Portugal</option>
               <option value="Puerto Rico">Puerto Rico</option>
               <option value="Qatar">Qatar</option>
               <option value="Réunion">Réunion</option>
               <option value="Romania">Romania</option>
               <option value="Russia">Russia</option>
               <option value="Rwanda">Rwanda</option>
               <option value="Saint Barthélemy">Saint Barthélemy</option>
               <option value="Saint Helena">Saint Helena</option>
               <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
               <option value="Saint Lucia">Saint Lucia</option>
               <option value="Saint Martin">Saint Martin</option>
               <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
               <option value="Saint Vincent and the Grenadines">Saint Vincent and the Grenadines</option>
               <option value="Samoa">Samoa</option>
               <option value="San Marino">San Marino</option>
               <option value="São Tomé and Príncipe">São Tomé and Príncipe</option>
               <option value="Saudi Arabia">Saudi Arabia</option>
               <option value="Senegal">Senegal</option>
               <option value="Serbia">Serbia</option>
               <option value="Seychelles">Seychelles</option>
               <option value="Sierra Leone">Sierra Leone</option>
               <option value="Singapore">Singapore</option>
               <option value="Slovakia">Slovakia</option>
               <option value="Slovenia">Slovenia</option>
               <option value="Solomon Islands">Solomon Islands</option>
               <option value="Somalia">Somalia</option>
               <option value="South Africa">South Africa</option>
               <option value="South Georgia and the South Sandwich Islands">South Georgia and the South Sandwich Islands</option>
               <option value="South Korea">South Korea</option>
               <option value="Spain">Spain</option>
               <option value="Sri Lanka">Sri Lanka</option>
               <option value="Sudan">Sudan</option>
               <option value="Suriname">Suriname</option>
               <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
               <option value="Swaziland">Swaziland</option>
               <option value="Sweden">Sweden</option>
               <option value="Switzerland">Switzerland</option>
               <option value="Syria">Syria</option>
               <option value="Taiwan">Taiwan</option>
               <option value="Tajikistan">Tajikistan</option>
               <option value="Tanzania">Tanzania</option>
               <option value="Thailand">Thailand</option>
               <option value="Timor-Leste">Timor-Leste</option>
               <option value="Togo">Togo</option>
               <option value="Tokelau">Tokelau</option>
               <option value="Tonga">Tonga</option>
               <option value="Trinidad and Tobago">Trinidad and Tobago</option>
               <option value="Tunisia">Tunisia</option>
               <option value="Turkey">Turkey</option>
               <option value="Turkmenistan">Turkmenistan</option>
               <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
               <option value="Tuvalu">Tuvalu</option>
               <option value="Uganda">Uganda</option>
               <option value="Ukraine">Ukraine</option>
               <option value="United Arab Emirates">United Arab Emirates</option>
               <option value="United Kingdom">United Kingdom</option>
               <option selected="selected" value="United States">United States</option>
               <option value="UY">UY</option>
               <option value="U.S. Minor Outlying Islands">U.S. Minor Outlying Islands</option>
               <option value="U.S. Virgin Islands">U.S. Virgin Islands</option>
               <option value="Uzbekistan">Uzbekistan</option>
               <option value="Vanuatu">Vanuatu</option>
               <option value="Vatican City">Vatican City</option>
               <option value="Venezuela">Venezuela</option>
               <option value="Vietnam">Vietnam</option>
               <option value="Wallis and Futuna">Wallis and Futuna</option>
               <option value="Western Sahara">Western Sahara</option>
               <option value="Yemen">Yemen</option>
               <option value="Zambia">Zambia</option>
               <option value="Zimbabwe">Zimbabwe</option>
            </select>
            <br>
         </div>
         <div class="fieldlablevalue">
            <h3>* Email</h3>
            <input type="text" class="last_name required-entry input-text required-entry" value="" name="last_name" id="last_name" style="width:333px;">                 
         </div>
         <br>
         <div class=""></div>
         <br>
         <input type="button" class="pre_btn" value="Previous" /> 
         <input type="submit" class="submit_btn" value="Submit" />
                 
      </fieldset>
      <?php }?>
      <div class="disclaimer" style="display: none;">*Tracking information will be sent to the e-mail provided above.</div> 
   </form>
</div>
<div class="govnotice">
   <h2 class="disclaimerage"><span style="color: #bd0606;">*Must be Age 18+ to order/redeem. 19+ in AL, AK, UT, NJ.</span></h2>
</div>
<!--</div>-->