
<form enctype="multipart/form-data" method="post" action="<?php echo Mage::getUrl('frontdeals/index/step2/id/'.$this->getRequest()->getParam("id")) ?>" id="edit_form"><div><input type="hidden" value="zaVJBOdoFbW8wj2k" name="form_key"></div><div style="" id="deals_tabs_form_section_content"><div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Shipping Information</h4>
    <div class="form-buttons"></div>
</div>
    <div id="deals_form" class="fieldset ">
    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>              
<tr>
        <td class="label"><label for="first_name">First Name <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="first_name" id="first_name">            </td>
    </tr>
<tr>
        <td class="label"><label for="last_name">Last Name <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="last_name" id="last_name">            </td>
    </tr>
<tr>
        <td class="label"><label for="company">Company <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="company" id="company">            </td>
    </tr>
<tr>
        <td class="label"><label for="address">Address <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="address" id="address">            </td>
    </tr>
<tr>
        <td class="label"><label for="city">City <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="city" id="city">            </td>
    </tr>
<tr>
        <td class="label"><label for="state">State <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="state" id="state">            </td>
    </tr>
<tr>
        <td class="label"><label for="zip">Zip <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="zip" id="zip">            </td>
    </tr>
<tr>
        <td class="label"><label for="country">Country <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="country" id="country">            </td>
    </tr>
<tr>
        <td class="label"><label for="telephone">Telephone <span class="required">*</span></label></td>
    <td class="value">
        <input type="text" class="required-entry input-text required-entry" value="" name="telephone" id="telephone">            </td>
    </tr>
<tr>
        <td class="label"><label for="fax">Fax</label></td>
    <td class="value">
        <input type="text" class=" input-text" value="" name="fax" id="fax">            </td>
    </tr>
    <tr>
        <td colspan="2" class="label"><button type="submit" title="<?php echo $this->__('Reedem') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button> </td>
    </tr>
            </tbody>
        </table>
            </div>
        </div>
</div>
</div></form>