<script type="text/javascript" src="<?php echo $this->getJsUrl('tiny_mce/tiny_mce.js') ?>"></script>
<div class="page-title">
    <h1><?php echo $this->__('Submit Ticket') ?></h1>
</div>
<div class="fieldset" style="padding-left: 33px; padding-right: 33px;"> 
<?php echo $this->getMessagesBlock()->getGroupedHtml() ;

echo $this->getLayout()->createBlock('helpdesk/supportinfo')->toHtml();
echo "<br />";
echo $this->getLayout()->createBlock('helpdesk/ticketcontainer')->toHtml();
?>
</div>