<?php
/**
 * Overridden template
 */
?>
<script type="text/javascript">
optionTemplate = '<div id="<?php echo $this->getFieldId() ?>_{{index}}"  class="option-box"> ' +
'<div class="option-title"> ' +
    '<label for="<?php echo $this->getFieldName() ?>[{{index}}][title]"><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Default Title')) ?> <span class="required">*</span></label>' +
    <?php if ($this->isDefaultStore()): ?>
    '<input class="input-text required-entry" type="text" name="<?php echo $this->getFieldName() ?>[{{index}}][title]" id="id_<?php echo $this->getFieldName() ?>_{{index}}_title" value="{{title}}">' +
    <?php else: ?>
    '<input class="input-text required-entry" type="text" name="<?php echo $this->getFieldName() ?>[{{index}}][default_title]" id="id_<?php echo $this->getFieldName() ?>_{{index}}_default_title" value="{{default_title}}">' +
    <?php endif; ?>
      
        
        
'<?php echo $this->jsQuoteEscape($this->getOptionDeleteButtonHtml()) ?>' +
'</div>' +
'<label for="<?php echo $this->getFieldName() ?>[{{index}}][sub_product_description]" id="id_<?php echo $this->getFieldName() ?>_{{index}}_label"><strong><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Description')) ?> </strong></label>' +
'<textarea rows="5" cols="160" name="<?php echo $this->getFieldName() ?>[{{index}}][sub_product_description]" id="id_<?php echo $this->getFieldName() ?>_{{index}}_sub_product_description">{{sub_product_description}}</textarea>' +
    '<table class="option-header" cellpadding="0" cellspacing="0">' +
        '<thead>' +
            '<tr>' +
                <?php if (!$this->isDefaultStore()): ?>
                '<th class="opt-title"><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Store View Title')) ?>  <span class="required">*</span></th>' +
                <?php endif; ?>
                '<th class="opt-type"><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Input Type')) ?></th>' +
                '<th class="opt-req"><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Is Required')) ?></th>' +
                '<th class="opt-order"><?php echo $this->jsQuoteEscape(Mage::helper('bundle')->__('Position')) ?></th>' +
                '<th>&nbsp;</th>' +
            '</tr>' +
        '</thead>' +
        '<tbody>' +
            '<tr>' +
                '<input type="hidden" id="<?php echo $this->getFieldId() ?>_id_{{index}}" name="<?php echo $this->getFieldName() ?>[{{index}}][option_id]" value="{{option_id}}">' +
                '<input type="hidden" name="<?php echo $this->getFieldName() ?>[{{index}}][delete]" value="" class="delete">' +
                <?php if (!$this->isDefaultStore()): ?>
                '<td><input class="input-text required-entry" type="text" name="<?php echo $this->getFieldName() ?>[{{index}}][title]" id="id_<?php echo $this->getFieldName() ?>_{{index}}_title_store" value="{{title}}"></td>' +
                <?php endif; ?>
                '<td><?php echo $this->getTypeSelectHtml() ?></td>' +
                '<td><?php echo $this->getRequireSelectHtml() ?></td>' +
                '<td><input class="input-text validate-zero-or-greater" type="text" name="<?php echo $this->getFieldName() ?>[{{index}}][position]" value="{{position}}"></td>' +
                '<td>&nbsp;<?php echo $this->jsQuoteEscape($this->getAddSelectionButtonHtml()) ?></td>' +
            '</tr>' +
        '</tbody>' +
    '</table>' +
    '<div id="<?php echo $this->getFieldId() ?>_search_{{index}}">' +
    '</div>' +
'</div>';
</script>


<?php echo $this->getSelectionHtml() ?>
    
<script type="text/javascript">

function handleEditor(id) {
	
			tinyMCE.init({
			mode : "exact",
			elements: id,
			theme : "advanced",
			plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_path_location : "bottom",
        extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
        theme_advanced_resize_horizontal : 'true',
        theme_advanced_resizing : 'true',
        apply_source_formatting : 'true',
        convert_urls : 'false',
        force_br_newlines : 'true',
        doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

      });	
	
	
}

function changeInputType(oldObject, oType) {
    var newObject = document.createElement('input');
    newObject.type = oType;
    if(oldObject.size) newObject.size = oldObject.size;
    if(oldObject.value) newObject.value = oldObject.value;
    if(oldObject.name) newObject.name = oldObject.name;
    if(oldObject.id) newObject.id = oldObject.id;
    if(oldObject.onclick) newObject.onclick = oldObject.onclick;
    if(oldObject.className) newObject.className = oldObject.className;
    oldObject.parentNode.replaceChild(newObject,oldObject);
    return newObject;
}

Bundle.Option = Class.create();

Bundle.Option.prototype = {
    idLabel : '<?php echo $this->getFieldId() ?>',
    top : '',
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : '',
    itemsCount : 0,
    initialize : function(template) {
        this.templateText = template;
        this.top = $('product_bundle_container_top');
    },

    add : function(data) {
        
        if(!data){
            data = {};
            this.top = $('product_bundle_container_top');
        } else {
            data.title = data.title.replace('"', "&quot;");
        }

        data.index = this.itemsCount++;

        this.template = new Template(this.templateText, this.templateSyntax);

        Element.insert(this.top, {'after':this.template.evaluate(data)});

        this.top = $(this.idLabel + '_' + data.index);

        //set selected type
        if (data.type) {
            $A($(this.idLabel + '_'+data.index+'_type').options).each(function(option){
                if (option.value==data.type) option.selected = true;
            });
        }

        //set selected is_require
        if (data.required) {
            $A($(this.idLabel + '_'+data.index+'_required').options).each(function(option){
                if (option.value==data.required) option.selected = true;
            });
        }

        // rebind change notifications
        varienWindowOnload(true);
		var textarea_id = "id_bundle_options_" + data.index + "_sub_product_description";
		var label_id = "id_bundle_options_" + data.index + "_label";
		var editor_id = "id_bundle_options_" + data.index + "_sub_product_description_tbl";
		if(data.type == 'grid') {
			handleEditor(textarea_id);
					
		} else {
			document.getElementById(textarea_id).style.display = "none";
			document.getElementById(label_id).style.display = "none";
		}
		
        return data.index;
    },

    remove : function(event){
        var element = $(Event.findElement(event, 'div')).parentNode;
        if(element){
            Element.select(element, '.delete').each(function(elem){elem.value='1'});
            Element.select(element, ['input', 'select']).each(function(elem){elem.hide(); elem.className = '';});
            Element.hide(element);
        }
    },

    changeType : function(event) {
        var element = Event.element(event);
		
        parts = element.id.split('_');
        i = parts[2];
		var textarea_id = "id_bundle_options_" + i + "_sub_product_description";
		var label_id = "id_bundle_options_" + i + "_label";
		var editor_id = "id_bundle_options_" + i + "_sub_product_description_tbl";
		if(element.value == 'grid'){
			document.getElementById(textarea_id).style.display = "block";
			document.getElementById(label_id).style.display = "block";
			handleEditor(textarea_id);
		} else {
			document.getElementById(editor_id).style.display = "none";
			document.getElementById(label_id).style.display = "none";
		}

        if (element.value == 'multi' || element.value == 'checkbox') {
            
            var requiredElementId = element.id.replace('type', 'required'); 
            $$('#' + requiredElementId + ' option').each(function(option){
                if(option.readAttribute('value') == 1){
                    option.selected = true;
                    throw $break;
                }
            });

            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' tr.selection input.default'));
            inputs.each(
                function(elem){
                    //elem.type = "checkbox";
                    changeInputType(elem, 'checkbox');
                }
            );
            /**
             * Hide not needed elements (user defined qty select box)
             */
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .qty-box'));
            inputs.each(
                function(elem){
                    elem.hide();
                }
            );

            //show default box of hidden
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .default-box'));
            inputs.each(
                function(elem){
                    elem.show();
                }
            );

            //add required entry class again for default magento input types
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' tr.selection input.default-qty-box'));
            inputs.each(
                function(elem){
                    elem.addClassName('required-entry');
                    if(elem.value == 0){
                        elem.value = '';
                    }
                }
            ); 

        } else if(element.value == 'grid'){
            
			var requiredElementId = element.id.replace('type', 'required'); 
            $$('#' + requiredElementId + ' option').each(function(option){
                if(option.readAttribute('value') == 0){
                    option.selected = true;
                    throw $break;
                }
            });

            /**
             * Hide not needed elements (user defined qty select box)
             */
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .default-box'));
            inputs.each(
                function(elem){
                    elem.hide();
                }
            );

            /**
             * Show user defined select box
             */
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .qty-box'));
            inputs.each(
                function(elem){
                    elem.show();
                }
            );

            //remove required entry class for grid custom input types
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' tr.selection input.default-qty-box'));
            inputs.each(
                function(elem){
                    elem.removeClassName('required-entry');
                    
                    elem.value = parseInt(elem.value) > 0 ? elem.value : '';
                }
            ); 
            
        } else {
            
            var requiredElementId = element.id.replace('type', 'required'); 
            $$('#' + requiredElementId + ' option').each(function(option){
                if(option.readAttribute('value') == 1){
                    option.selected = true;
                    throw $break;
                }
            });

            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' tr.selection input.default'));
            have = false;
            for (j=0; j< inputs.length; j++) {
                //inputs[j].type = "radio";
                changeInputType(inputs[j], 'radio');
                if (inputs[j].checked && have) {
                    inputs[j].checked = false;
                } else {
                    have = true;
                }
            }

            /**
             * Show user defined select box
             */
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .qty-box'));
            inputs.each(
                function(elem){
                    elem.show();
                }
            );

            //show default box of hidden
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' .default-box'));
            inputs.each(
                function(elem){
                    elem.show();
                }
            );

            //add required entry class again for default magento input types
            inputs = $A($$('#' + bSelection.idLabel + '_box_' + i + ' tr.selection input.default-qty-box'));
            inputs.each(
                function(elem){
                    elem.addClassName('required-entry');
                    if(elem.value == 0){
                        elem.value = '';
                    }
                }
            ); 

        }


    },

    priceTypeFixed : function() {
        inputs = $A($$('.price-type-box'));
        inputs.each(
            function(elem){
                elem.show();
            }
        );
    },

    priceTypeDynamic : function() {
        inputs = $A($$('.price-type-box'));
        inputs.each(
            function(elem){
                elem.hide();
            }
        );
    }
}

var optionIndex = 0;
bOption = new Bundle.Option(optionTemplate);
//adding data to templates
<?php foreach ($this->getOptions() as $_option): ?>
optionIndex = bOption.add(<?php echo $_option->toJson() ?>);
<?php if ($_option->getSelections()):?>
    <?php foreach ($_option->getSelections() as $_selection): ?>
    <?php $_selection->setName($this->escapeHtml($_selection->getName())); ?>
bSelection.addRow(optionIndex, <?php echo $_selection->toJson() ?>);
    <?php endforeach; ?>
<?php endif; ?>
<?php endforeach; ?>
/**
 * Adding event on price type select box of product to hide or show prices for selections
 */
function togglePriceType() {
    if ($('price_type').value == '1') {
        bOption.priceTypeFixed();
    } else {
        bOption.priceTypeDynamic();
    }
}

togglePriceType();

Event.observe('price_type', 'change', togglePriceType);

</script>
