<?php

/**
 * Retail Evolved - Facebook Like Button
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA that is bundled with this
 * package in the file EVOLVED_EULA.txt.
 * It is also available through the world-wide-web at this URL:
 * http://retailevolved.com/eula-1-0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to service@retailevolved.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * You may edit this file, but only at your own risk, as long as it is within
 * the constraints of the license agreement. Before upgrading the module (not Magento), 
 * be sure to back up your original installation as the upgrade may override your
 * changes.
 *
 * @category   Evolved
 * @package    Evolved_Like
 * @copyright  Copyright (c) 2010 Kaelex Inc. DBA Retail Evolved (http://retailevolved.com)
 * @license    http://retailevolved.com/eula-1-0 (Retail Evolved EULA 1.0)
 */

?>
<?php if($_product = $this->getProduct()):
  $product_image = Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getSmallImage()); ?>
  <meta property="og:title" content="<?php echo htmlspecialchars($_product->getName()) ?>"/>
  <?php if(Mage::helper('evlike')->getLikeConfig('ev_facebook_app_id') && Mage::helper('evlike')->getLikeConfig('ev_enable_open_graph')): ?>
  <meta property="og:type" content="product"/>
  <meta property="og:url" content="<?php echo $this->getCurrentUrl() ?>"/>
  <?php endif; ?>
  <?php if($_product->getSmallImage() != 'no_selection'): ?>
  <meta property="og:image" content="<?php echo $product_image; ?>"/>
  <meta property="og:image:height" content="630"/>
  <?php  else: ?>
  <meta property="og:image" content="<?php echo $this->getSkinUrl('images/logo_fb.png') ?>"/>
  <meta property="og:image:width" content="1200"/>
  <meta property="og:image:height" content="630"/>
  <?php endif; ?>
  <?php 
  /*HCL-10 implement og & tc attributes on templates*/
  $ogDescription = $_product->getData('og_description');
  if( ! $ogDescription){
    $ogDescription = $_product->getMetaDescription();
  }
  /*Ends*/
  ?>
  
  <?php if($ogDescription):?>
    <meta property="og:description" content="<?php echo htmlspecialchars(strip_tags($ogDescription)) ?>"/>
  <?php endif; ?>

<?php elseif ($_category = Mage::registry('current_category')): ?>
    <meta property="og:title" content="<?php echo htmlspecialchars($_category->getName()) ?>"/>
    <?php if(Mage::helper('evlike')->getLikeConfig('ev_facebook_app_id') && Mage::helper('evlike')->getLikeConfig('ev_enable_open_graph')): ?>
     <meta property="og:type" content="article"/>
     <meta property="og:url" content="<?php echo $this->getCurrentUrl() ?>"/>
    <?php endif; ?>
    <?php 
    $category_image = $_category->getImageUrl();?>
    <meta property="og:image" content="<?php echo $this->getSkinUrl('images/logo_fb.png') ?>"/>
    <?php 
    /* HCL-8: Modified to add meta description(Start)*/
    $category = Mage::registry('current_category');
    //$category = Mage::getModel('catalog/category')->load($category->getId());

    $ogDescription = $category->getData('og_description');
    if( ! $ogDescription){
        $ogDescription = $category->getData('meta_description');    
    }
  ?>
  <?php if($ogDescription):?>
    <meta property="og:description" content="<?php echo htmlspecialchars(strip_tags($ogDescription)) ?>"/>
  <?php endif;?>
        
  <?php elseif (Mage::getSingleton('cms/page')->getId()): ?>
      
      <?php $_page = Mage::getSingleton('cms/page'); ?>
      <meta property="og:title" content="<?php echo htmlspecialchars($_page->getTitle()) ?>"/>
      <?php if(Mage::helper('evlike')->getLikeConfig('ev_facebook_app_id') && Mage::helper('evlike')->getLikeConfig('ev_enable_open_graph')): ?>
      <meta property="og:type" content="article"/>
      <meta property="og:url" content="<?php echo $this->getCurrentUrl() ?>"/>
      <?php endif; ?>

      <?php
      
      $descriptionCMS = $_page->getData('og_description');
      if( ! $descriptionCMS){
          $descriptionCMS =  $_page->getMetaDescription();
      }

      ?>

      <?php if($descriptionCMS): ?>
        <meta property="og:description" content="<?php echo htmlspecialchars(strip_tags($descriptionCMS)) ?>"/>
      <?php endif;?>
      
      <meta property="og:image" content="<?php echo $this->getSkinUrl('images/logo_fb.png') ?>"/>
      <meta property="og:image:width" content="1200"/>
      <meta property="og:image:height" content="630"/>

  <?php else: ?>

    <?php $_page = Mage::getSingleton('cms/page'); ?>
    <meta property="og:title" content="<?php echo htmlspecialchars($_page->getTitle()) ?>"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="<?php echo $this->getCurrentUrl() ?>"/>
    <meta property="og:description" content="<?php echo htmlspecialchars(strip_tags($_page->getMetaDescription())) ?>"/>
    <meta property="og:image" content="<?php echo $this->getSkinUrl('images/logo_fb.png') ?>"/>  
    <meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<?php endif; ?>

