<?php
/**
 * @package Halox_Registration
 */
$formElements = $this->getFormElements();
?>
<?php if ($this->isShowHeader()): ?>
    <div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Step 3 of 3') ?></h2>
<?php endif; ?>
    <div style="float: left;width:100%;">
        <ul class="form-list">
            <?php foreach ($formElements as $element): ?>
                <?php if($element->getType() == 'fieldset'):?>
                    <?php foreach($element->getElements() as $elem):?>
                        <?php $class = "";?>
                        <?php if(in_array($elem->getHtmlId(), array('wholesale_employees', 'buyer', 'buyer_email', 'owner', 'owner_email'))):?>
                        <?php $class .= 'width50'?>
                        <?php endif?>
                        <li class="fields <?php echo $class?>">
                            <div class="field">
                            <?php echo $elem->setNoSpan(true)->toHtml()?>        
                            </div>
                        </li>
                    <?php endforeach;?>    
                <?php endif?>    
            <?php endforeach; ?>
        </ul>
    </div>
    <!-- CUSTOM IMAGE AT THE RIGHT: <div style="float: right;"><img src="PATH HERE" /></div>-->
    <div style="clear: both;"></div>
<?php if ($this->isShowHeader()): ?>
    </div>
<?php endif; ?>
<?php if ($this->needRelations()): ?>
    <!-- Customer Attributes Relations -->
<?php endif; ?>