<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<?php
$_items = array();

$_itemsCollection = $this->getQuote()->getItemsCollection();

foreach ($_itemsCollection as $item) {

    if (!$item->isDeleted()) {

        if ($item->hasParentItemId()) {
            $parentItem = $_itemsCollection->getItemById($item->getParentItemId());
            if ($parentItem->getProductType() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
                $_items[] = $item;
            }
        } elseif ($item->getProductType() != Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
            $_items[] = $item;
        }
    }
}

//sort cart items in natural order(CASE-INSENSITIVE)
usort($_items, function($a, $b) {
    return strnatcasecmp($a->getName(), $b->getName());
});
?>
<?php
$isPrintpageEnable = $isPrintOnCartEnabled = NULL;
$isPageprintModuleAvailable = Mage::helper('core')->isModuleEnabled('Halox_Pageprint');
if ($isPageprintModuleAvailable) {
    $isPrintpageEnable = Mage::helper('pageprint')->isPrintpageEnable();
    $isPrintOnCartEnabled = Mage::helper('pageprint')->isPrintOnCartEnabled();
}
?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
        <?php if (!$this->hasError()): ?>
            <ul class="checkout-types">
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <div class="cart-table-wrap">

                <?php echo $this->getChildHtml('form_before') ?>

                <?php
                $updateUrl = $this->getUrl('checkout/cart/updatePost');

                $isWholesaleCartUpdateAvailable = Mage::helper('core')->isModuleEnabled('Halox_WholesaleCartUpdate');

                $isWholesaleCartUpdateEnabled = $isWholesaleCartUpdateAvailable ? Mage::helper('halox_wholesalecartupdate')->isModuleActive($this->getQuote()->getStoreId()) : false;

                if ($isWholesaleCartUpdateEnabled) {
                    $updateUrl = $this->getUrl('wholesalecartupdate/cart/updatePost');
                }
                ?>

                <form action="<?php echo $updateUrl ?>" method="post">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <button class="button2 btn-update" title="Update Shopping Cart" value="update_qty" name="update_cart_action" data-cart-item-update="" style="visibility:hidden;" type="submit"><span><span>Update Shopping Cart</span></span></button> 
                    <?php if ($isPrintpageEnable && $isPrintOnCartEnabled): ?>
                    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'cartprint/' ?>" target="_blank" class="print-cart glyphicon glyphicon-print"><?php echo $this->__('') ?></a>
                    <?php endif; ?>
                    <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Clear Shopping Cart')); ?>" class="button btn-empty clear-shopping-cart" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                    <div class="clearfix"></div>
                    <fieldset>
                        <table id="shopping-cart-table" class="data-table cart-table">
                            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                            <thead>
                                <tr class="first last">
                                    <th rowspan="1">&nbsp;</th>
                                    <th rowspan="1"><span class="nobr">Product Name</span></th>
                                    <th rowspan="1">&nbsp;</th>
                                    <th colspan="1" class="txt-center"><span class="nobr">Unit Price</span></th>
                                    <th rowspan="1" class="txt-center">Qty</th>
                                    <th class="last txt-right" colspan="1">Subtotal</th>
                                    <th rowspan="1">&nbsp;</th>
                                </tr>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                    <tr>
                                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                    </tr>
                                <?php endif; ?>
                            </thead>
                            <tfoot>
                                <tr>
                                    <td colspan="50" class="a-right">
                                        <?php if ($this->getContinueShoppingUrl()): ?>
                                            <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getUrl('') ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                        <?php endif; ?>
                                        <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>



                                        <!--[if lt IE 8]>
                                        <input type="hidden" id="update_cart_action_container" />
                                        <script type="text/javascript">
                                            //<![CDATA[
                                            Event.observe(window, 'load', function()
                                            {
                                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                                $emptyCartButton = $('empty_cart_button');
                                                $cartActionContainer = $('update_cart_action_container');
                                                if ($emptyCartButton && $cartActionContainer) {
                                                    Event.observe($emptyCartButton, 'click', function()
                                                    {
                                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                        $cartActionContainer.setValue('empty_cart');
                                                    });
                                                }
    
                                            });
                                        //]]>
                                        </script>
                                        <![endif]-->
                                    </td>
                                </tr>
                            </tfoot>
                            <tbody>
                                <?php foreach ($_items as $_item): ?>
                                    <?php
                                    $renderer = $this->getItemRenderer($_item->getProductType());
                                    //if cart item is child of a bundle item use bundle item renderer 
                                    //instead of default one
                                    if ($_item->hasParentItemId()) {
                                        $parentItem = $this->getQuote()->getItemById($_item->getParentItemId());
                                        if ($parentItem->getProductType() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
                                            $renderer = $this->getItemRenderer(Mage_Catalog_Model_Product_Type::TYPE_BUNDLE);
                                        }
                                    }

                                    $renderer->setItem($_item);
                                    ?> 
                                    <?php echo $renderer->toHtml() ?>   
                                <?php endforeach ?>
                            </tbody>
                        </table>
                        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
                        <script type="text/javascript">
                            //<![CDATA[
                            jQuery(function ($) {
                                $(".cart .discount h2,.cart .shipping h2").click(function () {
                                    if ($(this).hasClass('opened')) {
                                        $(this).removeClass('opened');
                                        $(this).next().slideUp();
                                    } else {
                                        $(this).addClass('opened');
                                        $(this).next().slideDown();
                                    }
                                });
                            })
                            //]]>
                        </script>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3">
            <div class="cart-collaterals">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php
                if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping');
                endif;
                ?>
                <?php echo $this->getChildHtml('coupon') ?>
                <div class="totals">
                    <h2><?php echo $this->__('Cart Totals') ?></h2>
                    <div>
                        <?php echo $this->getChildHtml('totals'); ?>
                        <?php if (!$this->hasError()): ?>
                            <ul class="checkout-types">
                                <?php foreach ($this->getMethods('methods') as $method): ?>
                                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                        <li><?php echo $methodHtml; ?></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>
<script type="text/javascript">
    jQuery(function ($) {
        $(".qty_inc_cart").unbind('click').click(function () {
            if ($(this).parent().parent().children("input.qty").is(':enabled')) {
                $(this).parent().parent().children("input.qty").val((+$(this).parent().parent().children("input.qty").val() + 1) || 0);
                $(this).parent().parent().children("input.qty").focus();
                $(this).focus();
            }
        });
        $(".qty_dec_cart").unbind('click').click(function () {
            if ($(this).parent().parent().children("input.qty").is(':enabled')) {
                $(this).parent().parent().children("input.qty").val(($(this).parent().parent().children("input.qty").val() - 1 > 0) ? ($(this).parent().parent().children("input.qty").val() - 1) : 1);
                $(this).parent().parent().children("input.qty").focus();
                $(this).focus();
            }
        });
    });
</script>