
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('helpdesk')->__('Customer Information') ?></h4>
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label for="shareinfo"><?php echo Mage::helper('helpdesk')->__('Content') ?></label></td>
                        <td >
	                        <textarea cols="15" rows="2" style="width: 600px; height: 200px;" title="shareinfo" name="shareinfo" id="shareinfo"><?php echo $this->getContentShare();?></textarea>
                        </td>             
                    </tr>          
                </tbody>
            </table>
        </div>
    </div>
</div>
